# Thesis — Stage 1 Weighted + Stage 2 Oversampling + Threshold, with Optuna

This notebook adds **Optuna hyperparameter tuning** on top of the base experiment.
The EDA, preprocessing, train/validation/test splits, tokenization, and metrics are
**identical** to the base notebook. The only additions are:

- an Optuna `study` per stage that searches over `learning_rate`, `num_train_epochs`,
  `per_device_train_batch_size`, and `weight_decay`;
- each trial trains on the **train** split and is scored on the **validation** split
  (never the test set), so tuning never sees the held-out test data;
- Stage 1 optimizes toxic-class **F1**; Stage 2 optimizes **macro F1**;
- after the search, the best hyperparameters are used to train a final model, which is
  then evaluated once on the untouched **test** set (with decision-threshold tuning
  done on validation).

`N_TRIALS` is kept small so the notebook finishes in reasonable time on Kaggle; raise it
for a more thorough search.

**This variant keeps all 5 Stage-2 labels.** Stage 1 uses a class-weighted
CrossEntropyLoss; Stage 2 uses random oversampling of the training split. Both stages
add per-label / toxic-class decision-threshold tuning on validation.

In [1]:
# Install Optuna if it isn't already available in the environment.
# On Kaggle this is usually a no-op after the first run.
!pip install -q optuna

In [2]:
import pandas as pd
import numpy as np
import tqdm

from sklearn.model_selection import train_test_split
from datasets import Dataset, DatasetDict
from huggingface_hub import login

import torch
from torch import nn
import torch.nn.functional as F
from sklearn.utils.class_weight import compute_class_weight

import optuna

import ast
import re

# Silence transformers' informational/warning logs (e.g. legacy LayerNorm
# gamma/beta key-name notices when Trainer reloads the best checkpoint).
# Doesn't affect training/evaluation, only console noise.
from transformers.utils import logging as hf_logging
hf_logging.set_verbosity_error()

In [3]:
df = pd.read_csv("/kaggle/input/datasets/evelynuntariady/thesis/data_thesis_majority_vote.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26379 entries, 0 to 26378
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     26379 non-null  int64
 1   text_id                        26379 non-null  object
 2   annotators_id                  26379 non-null  object
 3   text                           26379 non-null  object
 4   topic                          26379 non-null  object
 5   is_noise_or_spam_text          26379 non-null  int64
 6   toxicity                       26379 non-null  int64
 7   polarized                      26379 non-null  int64
 8   profanity_obscenity            26379 non-null  int64
 9   threat_incitement_to_violence  26379 non-null  int64
 10  insults                        26379 non-null  int64
 11  identity_attack                26379 non-null  int64
 12  sexually_explicit              26379 non-null  int64
 13  cleaned_text                   26379 non-null  object
 14  processed_text                 26379 non-null  object
dtypes: int64(9), object(6)
memory usage: 3.0+ MB

In [5]:
df.head()

,Unnamed: 0,text_id,annotators_id,text,topic,is_noise_or_spam_text,toxicity,polarized,profanity_obscenity,threat_incitement_to_violence,insults,identity_attack,sexually_explicit,cleaned_text,processed_text
0,0,2026-01-01 00:00:00,"['7', '15']",Wajah Jurnalis Dibalut Perban Saat Melaporkan ...,UNKNOWN,0,0,0,0,0,0,0,0,Wajah jurnalis dibalut perban saat melaporkan ...,wajah jurnalis dibalut perban saat melaporkan ...
1,1,2026-01-10 00:00:00,"['7', '15']",Elektabilitas Paslon 02 sebentar lagi terjun b...,Disabilitas,0,0,1,0,0,0,0,0,Elektabilitas pasangan calon 02 sebentar lagi ...,elektabilitas pasangan calon sebentar lagi ter...
2,2,1-1001,"['10', '18']","Kristen, Hindu, Islam dapat perlakuan istimewa...",Kristen,0,0,1,0,0,0,0,0,"Kristen, Hindu, Islam dapat perlakuan istimewa...","kristen, hindu, islam dapat perlakuan istimewa..."
3,3,1-1004,"['10', '18']","Masyarakat Kristen, Hindu, Budha, dan etnis Ti...","Kristen, Tionghoa",0,0,0,0,0,0,0,0,"Masyarakat Kristen, Hindu, Buddha, dan etnis T...","masyarakat kristen, hindu, buddha, dan etnis t..."
4,4,1-1005,"['10', '18']",Cina Mengirimkan Satelit Penginderaan Jauh Bar...,Tionghoa,0,0,0,0,0,0,0,0,Cina mengirimkan satelit penginderaan jauh bar...,cina mengirimkan satelit penginderaan jauh bar...

In [6]:
def transform_datetime_id(text_id_str):
    # Regex to match the datetime pattern like 'YYYY-MM-DD HH:MM:SS'
    match = re.match(r'(\d+)-(\d{2})-(\d{2}) \d{2}:\d{2}:\d{2}', str(text_id_str))
    if match:
        year_part = match.group(1)
        month_part = int(match.group(2))
        day_part = int(match.group(3))

        if year_part == '2026':
            # For year 2026, format as month-day (e.g. '1-1')
            return f"{month_part}-{day_part}"
        else:
            # For other years, format as month-original_year (e.g. '2-8783')
            return f"{month_part}-{year_part}"
    else:
        return text_id_str  # Return original if pattern doesn't match

# Apply this transformation to the 'text_id' column of your DataFrame
df['text_id'] = df['text_id'].apply(transform_datetime_id)

In [7]:
cols = [
'is_noise_or_spam_text',
'toxicity',
'polarized',
'profanity_obscenity',
'threat_incitement_to_violence',
'insults',
'identity_attack',
'sexually_explicit'
]

for col in cols:
    df[col] = df[col].apply(lambda x: ast.literal_eval(x) if isinstance(x,str) else x)

In [8]:
df_main = df.copy()

In [9]:
df_main = df_main[df_main['is_noise_or_spam_text'] == 0]

In [10]:
df_main.isnull().sum()

Unnamed: 0                       0
text_id                          0
annotators_id                    0
text                             0
topic                            0
is_noise_or_spam_text            0
toxicity                         0
polarized                        0
profanity_obscenity              0
threat_incitement_to_violence    0
insults                          0
identity_attack                  0
sexually_explicit                0
cleaned_text                     0
processed_text                   0
dtype: int64

In [11]:
slang_dict = {
    "gk": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "yg": "yang",
    "lu": "kamu",
    "loe": "kamu",
    "gw": "saya",
    "gue": "saya",
    "bgt": "banget",
    "dgn": "dengan",
    "krn": "karena",
    "aja": "saja",
    "trs": "terus"
}

In [12]:
import re

def normalize_slang(text, slang_dict):
    words = text.split()
    return " ".join([slang_dict.get(w.lower(), w) for w in words])

def preprocess_text(text, slang_dict, lowercase=True):
    if not isinstance(text, str):
        return ""

    # 1. remove username (@user)
    text = re.sub(r'@\w+', '', text)

    # 2. remove URL
    text = re.sub(r'http\S+|www\.\S+', '', text)

    # 3. remove numbers
    text = re.sub(r'\d+', '', text)

    # 4. remove unwanted symbols (keep .,!?)
    text = re.sub(r'[^\w\s.,!?]', '', text)

    # 5. normalize slang
    text = normalize_slang(text, slang_dict)

    # 6. normalize repeated chars (contoh: anjiiing -> anjiing)
    text = re.sub(r'(.)\1{2,}', r'\1\1', text)

    # 7. lowercase (optional)
    if lowercase:
        text = text.lower()

    # 8. remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [13]:
from tqdm import tqdm
tqdm.pandas()

df_main["processed_text"] = (
    df_main["cleaned_text"]
    .fillna("")
    .astype(str)
    .progress_apply(
        lambda x: preprocess_text(x, slang_dict)
    )
)

100%|██████████| 26379/26379 [00:01<00:00, 21396.37it/s]

In [14]:
df_main['toxicity'].value_counts()

toxicity
0    23980
1     2399
Name: count, dtype: int64

In [15]:
df_main['profanity_obscenity'].value_counts()

profanity_obscenity
0    26018
1      361
Name: count, dtype: int64

In [16]:
df_main['insults'].value_counts()

insults
0    25315
1     1064
Name: count, dtype: int64

In [17]:
df_main['identity_attack'].value_counts()

identity_attack
0    25365
1     1014
Name: count, dtype: int64

# Stage 1 — Binary Toxicity (Weighted + Optuna)

In [ ]:
from huggingface_hub import login

login("")

In [19]:
x = df_main['processed_text']
y = df_main['toxicity']

In [20]:
x_train_full, x_test, y_train_full, y_test = train_test_split(
    x, y, test_size=0.2, stratify=y, random_state=42
)
x_train, x_val, y_train, y_val = train_test_split(
    x_train_full, y_train_full, test_size=0.125, stratify=y_train_full, random_state=42
)

print("Stage 1 split sizes:", {"train": len(x_train), "val": len(x_val), "test": len(x_test)})

Stage 1 split sizes: {'train': 18465, 'val': 2638, 'test': 5276}

In [21]:
# Class weights for Stage 1, computed from the TRAIN split only, used by the weighted
# CrossEntropyLoss below.
class_weights_s1 = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train),
    y=y_train
)
class_weights_s1 = torch.tensor(class_weights_s1, dtype=torch.float)
print("Stage 1 class weights (class 0, class 1):", class_weights_s1)

Stage 1 class weights (class 0, class 1): tensor([0.5500, 5.4988])

In [22]:
train_df = pd.DataFrame({"processed_text": x_train, "label": y_train})
val_df = pd.DataFrame({"processed_text": x_val, "label": y_val})
test_df = pd.DataFrame({"processed_text": x_test, "label": y_test})

dataset = DatasetDict({
    "train": Dataset.from_pandas(train_df),
    "validation": Dataset.from_pandas(val_df),
    "test": Dataset.from_pandas(test_df)
})

In [23]:
from transformers import (
    AutoTokenizer,
    Trainer,
    TrainingArguments,
    AutoModelForSequenceClassification,
    EarlyStoppingCallback,
)
tokenizer = AutoTokenizer.from_pretrained("indolem/indobertweet-base-uncased")

In [24]:
def tokenize(batch):
    return tokenizer(
        batch["processed_text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

In [25]:
tokenized_datasets_1 = dataset.map(tokenize, batched=True)

tokenized_datasets_1 = tokenized_datasets_1.remove_columns(["processed_text"])
tokenized_datasets_1 = tokenized_datasets_1.rename_column("label", "labels")
tokenized_datasets_1.set_format("torch")

train_dataset_1 = tokenized_datasets_1["train"]
val_dataset_1 = tokenized_datasets_1["validation"]
test_dataset_1 = tokenized_datasets_1["test"]

Map:   0%|          | 0/18465 [00:00<?, ? examples/s]

Map:   0%|          | 0/2638 [00:00<?, ? examples/s]

Map:   0%|          | 0/5276 [00:00<?, ? examples/s]

In [26]:
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    classification_report, auc, roc_curve, precision_recall_curve
)

def compute_metrics_s1(eval_pred):
    logits, labels = eval_pred
    preds = logits.argmax(axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1": f1_score(labels, preds),
        "recall": recall_score(labels, preds),
        "precision": precision_score(labels, preds),
        "roc_auc": auc(roc_curve(labels, preds)[0], roc_curve(labels, preds)[1])
    }

In [27]:
# Trainer that applies class weights to CrossEntropyLoss, used to handle label
# imbalance in Stage 1.
class WeightedTrainerSingleLabel(Trainer):
    def __init__(self, *args, class_weights=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits
        weight = self.class_weights.to(logits.device) if self.class_weights is not None else None
        loss_fct = nn.CrossEntropyLoss(weight=weight)
        # logits.size(-1) instead of model.config.num_labels: stays correct even if
        # Trainer wraps the model in nn.DataParallel (which doesn't expose .config).
        loss = loss_fct(logits.view(-1, logits.size(-1)), labels.view(-1))
        return (loss, outputs) if return_outputs else loss

## Optuna search — Stage 1 (weighted loss)

In [28]:
N_TRIALS = 10  # raise for a more thorough search

def model_init_s1():
    return AutoModelForSequenceClassification.from_pretrained(
        "indolem/indobertweet-base-uncased",
        num_labels=2
    )

def objective_s1(trial):
    import shutil, os
    lr = trial.suggest_float("learning_rate", 1e-5, 5e-5, log=True)
    epochs = trial.suggest_int("num_train_epochs", 3, 6)
    batch_size = trial.suggest_categorical("per_device_train_batch_size", [8, 16])
    weight_decay = trial.suggest_float("weight_decay", 0.0, 0.1)

    args = TrainingArguments(
        output_dir=f"./optuna_s1/trial_{trial.number}",
        num_train_epochs=epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=16,
        learning_rate=lr,
        weight_decay=weight_decay,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        save_only_model=True,      # don't persist optimizer state during search (saves disk)
        save_total_limit=1,        # keep only the best checkpoint per trial
        metric_for_best_model="f1",
        greater_is_better=True,
        remove_unused_columns=False,
        logging_steps=50,
        disable_tqdm=True,
        report_to=[],
    )

    trainer = WeightedTrainerSingleLabel(
        model_init=model_init_s1,
        args=args,
        train_dataset=train_dataset_1,
        eval_dataset=val_dataset_1,
        compute_metrics=compute_metrics_s1,
        class_weights=class_weights_s1,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
    )
    try:
        trainer.train()
        metrics = trainer.evaluate()
        return metrics["eval_f1"]
    finally:
        # Free disk between trials: Kaggle's working dir fills up fast, and a
        # half-written checkpoint is what triggers the torch.save iostream error.
        shutil.rmtree(f"./optuna_s1/trial_{trial.number}", ignore_errors=True)

study_s1 = optuna.create_study(direction="maximize", study_name="stage1_weighted")
study_s1.optimize(objective_s1, n_trials=N_TRIALS)

print("Best Stage 1 params:", study_s1.best_params)
print("Best Stage 1 validation F1:", study_s1.best_value)

[I 2026-09-22 08:21:56,920] A new study created in memory with name: stage1_weighted

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

{'loss': '0.709', 'grad_norm': '10.86', 'learning_rate': '4.055e-05', 'epoch': '0.04329'}
{'loss': '0.5505', 'grad_norm': '19.25', 'learning_rate': '4.019e-05', 'epoch': '0.08658'}
{'loss': '0.6113', 'grad_norm': '4.096', 'learning_rate': '3.984e-05', 'epoch': '0.1299'}
{'loss': '0.5894', 'grad_norm': '14.82', 'learning_rate': '3.949e-05', 'epoch': '0.1732'}
{'loss': '0.533', 'grad_norm': '9.891', 'learning_rate': '3.913e-05', 'epoch': '0.2165'}
{'loss': '0.6555', 'grad_norm': '5.839', 'learning_rate': '3.878e-05', 'epoch': '0.2597'}
{'loss': '0.6413', 'grad_norm': '11.57', 'learning_rate': '3.842e-05', 'epoch': '0.303'}
{'loss': '0.7053', 'grad_norm': '6.448', 'learning_rate': '3.807e-05', 'epoch': '0.3463'}
{'loss': '0.4906', 'grad_norm': '11.44', 'learning_rate': '3.772e-05', 'epoch': '0.3896'}
{'loss': '0.6606', 'grad_norm': '4.87', 'learning_rate': '3.736e-05', 'epoch': '0.4329'}
{'loss': '0.687', 'grad_norm': '3.558', 'learning_rate': '3.701e-05', 'epoch': '0.4762'}
{'loss': '0.5646', 'grad_norm': '4.277', 'learning_rate': '3.665e-05', 'epoch': '0.5195'}
{'loss': '0.5158', 'grad_norm': '2.463', 'learning_rate': '3.63e-05', 'epoch': '0.5628'}
{'loss': '0.5192', 'grad_norm': '4.701', 'learning_rate': '3.595e-05', 'epoch': '0.6061'}
{'loss': '0.6156', 'grad_norm': '7.005', 'learning_rate': '3.559e-05', 'epoch': '0.6494'}
{'loss': '0.5522', 'grad_norm': '3.578', 'learning_rate': '3.524e-05', 'epoch': '0.6926'}
{'loss': '0.5254', 'grad_norm': '27.04', 'learning_rate': '3.488e-05', 'epoch': '0.7359'}
{'loss': '0.6223', 'grad_norm': '18.9', 'learning_rate': '3.453e-05', 'epoch': '0.7792'}
{'loss': '0.5384', 'grad_norm': '13.22', 'learning_rate': '3.418e-05', 'epoch': '0.8225'}
{'loss': '0.5038', 'grad_norm': '17', 'learning_rate': '3.382e-05', 'epoch': '0.8658'}
{'loss': '0.4599', 'grad_norm': '8.461', 'learning_rate': '3.347e-05', 'epoch': '0.9091'}
{'loss': '0.5603', 'grad_norm': '13.74', 'learning_rate': '3.311e-05', 'epoch': '0.9524'}
{'loss': '0.5706', 'grad_norm': '5.884', 'learning_rate': '3.276e-05', 'epoch': '0.9957'}
{'eval_loss': '0.5189', 'eval_accuracy': '0.8616', 'eval_f1': '0.4702', 'eval_recall': '0.675', 'eval_precision': '0.3608', 'eval_roc_auc': '0.7777', 'eval_runtime': '13.37', 'eval_samples_per_second': '197.4', 'eval_steps_per_second': '6.21', 'epoch': '1'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.4241', 'grad_norm': '21.45', 'learning_rate': '3.241e-05', 'epoch': '1.039'}
{'loss': '0.5341', 'grad_norm': '13.89', 'learning_rate': '3.205e-05', 'epoch': '1.082'}
{'loss': '0.4196', 'grad_norm': '3.676', 'learning_rate': '3.17e-05', 'epoch': '1.126'}
{'loss': '0.3859', 'grad_norm': '2.425', 'learning_rate': '3.134e-05', 'epoch': '1.169'}
{'loss': '0.4635', 'grad_norm': '11.6', 'learning_rate': '3.099e-05', 'epoch': '1.212'}
{'loss': '0.4267', 'grad_norm': '7.031', 'learning_rate': '3.063e-05', 'epoch': '1.255'}
{'loss': '0.5316', 'grad_norm': '11.87', 'learning_rate': '3.028e-05', 'epoch': '1.299'}
{'loss': '0.4254', 'grad_norm': '3.927', 'learning_rate': '2.993e-05', 'epoch': '1.342'}
{'loss': '0.5192', 'grad_norm': '1.856', 'learning_rate': '2.957e-05', 'epoch': '1.385'}
{'loss': '0.3595', 'grad_norm': '39.83', 'learning_rate': '2.922e-05', 'epoch': '1.429'}
{'loss': '0.5249', 'grad_norm': '13.02', 'learning_rate': '2.886e-05', 'epoch': '1.472'}
{'loss': '0.4182', 'grad_norm': '20.11', 'learning_rate': '2.851e-05', 'epoch': '1.515'}
{'loss': '0.4908', 'grad_norm': '3.353', 'learning_rate': '2.816e-05', 'epoch': '1.558'}
{'loss': '0.3706', 'grad_norm': '7.015', 'learning_rate': '2.78e-05', 'epoch': '1.602'}
{'loss': '0.4707', 'grad_norm': '1.265', 'learning_rate': '2.745e-05', 'epoch': '1.645'}
{'loss': '0.4665', 'grad_norm': '1.04', 'learning_rate': '2.709e-05', 'epoch': '1.688'}
{'loss': '0.5165', 'grad_norm': '0.8677', 'learning_rate': '2.674e-05', 'epoch': '1.732'}
{'loss': '0.4998', 'grad_norm': '49.27', 'learning_rate': '2.639e-05', 'epoch': '1.775'}
{'loss': '0.5623', 'grad_norm': '4.856', 'learning_rate': '2.603e-05', 'epoch': '1.818'}
{'loss': '0.4772', 'grad_norm': '8.04', 'learning_rate': '2.568e-05', 'epoch': '1.861'}
{'loss': '0.4754', 'grad_norm': '6.982', 'learning_rate': '2.532e-05', 'epoch': '1.905'}
{'loss': '0.3712', 'grad_norm': '4.653', 'learning_rate': '2.497e-05', 'epoch': '1.948'}
{'loss': '0.5553', 'grad_norm': '6', 'learning_rate': '2.462e-05', 'epoch': '1.991'}
{'eval_loss': '0.6902', 'eval_accuracy': '0.9117', 'eval_f1': '0.5095', 'eval_recall': '0.5042', 'eval_precision': '0.5149', 'eval_roc_auc': '0.7283', 'eval_runtime': '13.31', 'eval_samples_per_second': '198.1', 'eval_steps_per_second': '6.234', 'epoch': '2'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.2141', 'grad_norm': '5.592', 'learning_rate': '2.426e-05', 'epoch': '2.035'}
{'loss': '0.3539', 'grad_norm': '29.55', 'learning_rate': '2.391e-05', 'epoch': '2.078'}
{'loss': '0.2594', 'grad_norm': '29.14', 'learning_rate': '2.355e-05', 'epoch': '2.121'}
{'loss': '0.2154', 'grad_norm': '110.5', 'learning_rate': '2.32e-05', 'epoch': '2.165'}
{'loss': '0.2116', 'grad_norm': '2.819', 'learning_rate': '2.285e-05', 'epoch': '2.208'}
{'loss': '0.3442', 'grad_norm': '7.931', 'learning_rate': '2.249e-05', 'epoch': '2.251'}
{'loss': '0.2319', 'grad_norm': '1.646', 'learning_rate': '2.214e-05', 'epoch': '2.294'}
{'loss': '0.3065', 'grad_norm': '4.204', 'learning_rate': '2.178e-05', 'epoch': '2.338'}
{'loss': '0.3408', 'grad_norm': '0.4468', 'learning_rate': '2.143e-05', 'epoch': '2.381'}
{'loss': '0.3048', 'grad_norm': '0.4967', 'learning_rate': '2.107e-05', 'epoch': '2.424'}
{'loss': '0.2936', 'grad_norm': '1.464', 'learning_rate': '2.072e-05', 'epoch': '2.468'}
{'loss': '0.3398', 'grad_norm': '6.026', 'learning_rate': '2.037e-05', 'epoch': '2.511'}
{'loss': '0.3999', 'grad_norm': '19.15', 'learning_rate': '2.001e-05', 'epoch': '2.554'}
{'loss': '0.3608', 'grad_norm': '4.467', 'learning_rate': '1.966e-05', 'epoch': '2.597'}
{'loss': '0.2784', 'grad_norm': '55.1', 'learning_rate': '1.93e-05', 'epoch': '2.641'}
{'loss': '0.362', 'grad_norm': '3.088', 'learning_rate': '1.895e-05', 'epoch': '2.684'}
{'loss': '0.3579', 'grad_norm': '10.67', 'learning_rate': '1.86e-05', 'epoch': '2.727'}
{'loss': '0.3016', 'grad_norm': '6.418', 'learning_rate': '1.824e-05', 'epoch': '2.771'}
{'loss': '0.4066', 'grad_norm': '3.997', 'learning_rate': '1.789e-05', 'epoch': '2.814'}
{'loss': '0.425', 'grad_norm': '7.813', 'learning_rate': '1.753e-05', 'epoch': '2.857'}
{'loss': '0.3569', 'grad_norm': '3.126', 'learning_rate': '1.718e-05', 'epoch': '2.9'}
{'loss': '0.2687', 'grad_norm': '22.85', 'learning_rate': '1.683e-05', 'epoch': '2.944'}
{'loss': '0.3297', 'grad_norm': '23.18', 'learning_rate': '1.647e-05', 'epoch': '2.987'}
{'eval_loss': '0.8401', 'eval_accuracy': '0.8908', 'eval_f1': '0.5068', 'eval_recall': '0.6167', 'eval_precision': '0.4302', 'eval_roc_auc': '0.7675', 'eval_runtime': '13.36', 'eval_samples_per_second': '197.5', 'eval_steps_per_second': '6.214', 'epoch': '3'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.2064', 'grad_norm': '81.71', 'learning_rate': '1.612e-05', 'epoch': '3.03'}
{'loss': '0.1888', 'grad_norm': '53.33', 'learning_rate': '1.576e-05', 'epoch': '3.074'}
{'loss': '0.1952', 'grad_norm': '0.4536', 'learning_rate': '1.541e-05', 'epoch': '3.117'}
{'loss': '0.1898', 'grad_norm': '2.161', 'learning_rate': '1.506e-05', 'epoch': '3.16'}
{'loss': '0.1784', 'grad_norm': '2.745', 'learning_rate': '1.47e-05', 'epoch': '3.203'}
{'loss': '0.2412', 'grad_norm': '11.34', 'learning_rate': '1.435e-05', 'epoch': '3.247'}
{'loss': '0.1049', 'grad_norm': '0.02327', 'learning_rate': '1.399e-05', 'epoch': '3.29'}
{'loss': '0.18', 'grad_norm': '59.65', 'learning_rate': '1.364e-05', 'epoch': '3.333'}
{'loss': '0.2138', 'grad_norm': '13.39', 'learning_rate': '1.328e-05', 'epoch': '3.377'}
{'loss': '0.1969', 'grad_norm': '0.1231', 'learning_rate': '1.293e-05', 'epoch': '3.42'}
{'loss': '0.08371', 'grad_norm': '0.03507', 'learning_rate': '1.258e-05', 'epoch': '3.463'}
{'loss': '0.2045', 'grad_norm': '0.1075', 'learning_rate': '1.222e-05', 'epoch': '3.506'}
{'loss': '0.2554', 'grad_norm': '82.02', 'learning_rate': '1.187e-05', 'epoch': '3.55'}
{'loss': '0.2231', 'grad_norm': '86.39', 'learning_rate': '1.151e-05', 'epoch': '3.593'}
{'loss': '0.238', 'grad_norm': '53.84', 'learning_rate': '1.116e-05', 'epoch': '3.636'}
{'loss': '0.1051', 'grad_norm': '0.4104', 'learning_rate': '1.081e-05', 'epoch': '3.68'}
{'loss': '0.2964', 'grad_norm': '0.09061', 'learning_rate': '1.045e-05', 'epoch': '3.723'}
{'loss': '0.1371', 'grad_norm': '0.03486', 'learning_rate': '1.01e-05', 'epoch': '3.766'}
{'loss': '0.1945', 'grad_norm': '0.05472', 'learning_rate': '9.744e-06', 'epoch': '3.81'}
{'loss': '0.196', 'grad_norm': '0.06113', 'learning_rate': '9.39e-06', 'epoch': '3.853'}
{'loss': '0.181', 'grad_norm': '0.189', 'learning_rate': '9.036e-06', 'epoch': '3.896'}
{'loss': '0.09709', 'grad_norm': '0.7175', 'learning_rate': '8.682e-06', 'epoch': '3.939'}
{'loss': '0.2057', 'grad_norm': '39.44', 'learning_rate': '8.328e-06', 'epoch': '3.983'}
{'eval_loss': '1.577', 'eval_accuracy': '0.9045', 'eval_f1': '0.4569', 'eval_recall': '0.4417', 'eval_precision': '0.4732', 'eval_roc_auc': '0.6962', 'eval_runtime': '13.37', 'eval_samples_per_second': '197.3', 'eval_steps_per_second': '6.206', 'epoch': '4'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'train_runtime': '1391', 'train_samples_per_second': '66.37', 'train_steps_per_second': '4.152', 'train_loss': '0.3861', 'epoch': '4'}

[I 2026-09-22 08:45:24,959] Trial 0 finished with value: 0.5125 and parameters: {'learning_rate': 4.089589405145897e-05, 'num_train_epochs': 5, 'per_device_train_batch_size': 8, 'weight_decay': 0.08638860109545607}. Best is trial 0 with value: 0.5125.

{'eval_loss': '0.6929', 'eval_accuracy': '0.9113', 'eval_f1': '0.5125', 'eval_recall': '0.5125', 'eval_precision': '0.5125', 'eval_roc_auc': '0.7319', 'eval_runtime': '13.36', 'eval_samples_per_second': '197.5', 'eval_steps_per_second': '6.215', 'epoch': '4'}

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

{'loss': '0.6839', 'grad_norm': '9.98', 'learning_rate': '1.503e-05', 'epoch': '0.04329'}
{'loss': '0.5594', 'grad_norm': '8.97', 'learning_rate': '1.492e-05', 'epoch': '0.08658'}
{'loss': '0.5029', 'grad_norm': '4.386', 'learning_rate': '1.481e-05', 'epoch': '0.1299'}
{'loss': '0.5075', 'grad_norm': '17.62', 'learning_rate': '1.47e-05', 'epoch': '0.1732'}
{'loss': '0.5357', 'grad_norm': '12.5', 'learning_rate': '1.459e-05', 'epoch': '0.2165'}
{'loss': '0.5614', 'grad_norm': '4.208', 'learning_rate': '1.448e-05', 'epoch': '0.2597'}
{'loss': '0.6368', 'grad_norm': '9.665', 'learning_rate': '1.437e-05', 'epoch': '0.303'}
{'loss': '0.5876', 'grad_norm': '4.478', 'learning_rate': '1.426e-05', 'epoch': '0.3463'}
{'loss': '0.4532', 'grad_norm': '12.07', 'learning_rate': '1.415e-05', 'epoch': '0.3896'}
{'loss': '0.5137', 'grad_norm': '9.35', 'learning_rate': '1.405e-05', 'epoch': '0.4329'}
{'loss': '0.5611', 'grad_norm': '5.564', 'learning_rate': '1.394e-05', 'epoch': '0.4762'}
{'loss': '0.5392', 'grad_norm': '6.58', 'learning_rate': '1.383e-05', 'epoch': '0.5195'}
{'loss': '0.4901', 'grad_norm': '5.554', 'learning_rate': '1.372e-05', 'epoch': '0.5628'}
{'loss': '0.4782', 'grad_norm': '4.361', 'learning_rate': '1.361e-05', 'epoch': '0.6061'}
{'loss': '0.5524', 'grad_norm': '10.2', 'learning_rate': '1.35e-05', 'epoch': '0.6494'}
{'loss': '0.4677', 'grad_norm': '5.977', 'learning_rate': '1.339e-05', 'epoch': '0.6926'}
{'loss': '0.4153', 'grad_norm': '9.558', 'learning_rate': '1.328e-05', 'epoch': '0.7359'}
{'loss': '0.6453', 'grad_norm': '26.22', 'learning_rate': '1.317e-05', 'epoch': '0.7792'}
{'loss': '0.5151', 'grad_norm': '18.21', 'learning_rate': '1.306e-05', 'epoch': '0.8225'}
{'loss': '0.4915', 'grad_norm': '4.632', 'learning_rate': '1.295e-05', 'epoch': '0.8658'}
{'loss': '0.4262', 'grad_norm': '3.607', 'learning_rate': '1.284e-05', 'epoch': '0.9091'}
{'loss': '0.5248', 'grad_norm': '16.36', 'learning_rate': '1.273e-05', 'epoch': '0.9524'}
{'loss': '0.5246', 'grad_norm': '5.009', 'learning_rate': '1.263e-05', 'epoch': '0.9957'}
{'eval_loss': '0.4424', 'eval_accuracy': '0.8287', 'eval_f1': '0.4461', 'eval_recall': '0.7583', 'eval_precision': '0.316', 'eval_roc_auc': '0.797', 'eval_runtime': '13.39', 'eval_samples_per_second': '197', 'eval_steps_per_second': '6.198', 'epoch': '1'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.4279', 'grad_norm': '39.73', 'learning_rate': '1.252e-05', 'epoch': '1.039'}
{'loss': '0.4622', 'grad_norm': '2.444', 'learning_rate': '1.241e-05', 'epoch': '1.082'}
{'loss': '0.372', 'grad_norm': '11.17', 'learning_rate': '1.23e-05', 'epoch': '1.126'}
{'loss': '0.3439', 'grad_norm': '2.978', 'learning_rate': '1.219e-05', 'epoch': '1.169'}
{'loss': '0.4697', 'grad_norm': '3.542', 'learning_rate': '1.208e-05', 'epoch': '1.212'}
{'loss': '0.3894', 'grad_norm': '7.559', 'learning_rate': '1.197e-05', 'epoch': '1.255'}
{'loss': '0.4623', 'grad_norm': '28.5', 'learning_rate': '1.186e-05', 'epoch': '1.299'}
{'loss': '0.4302', 'grad_norm': '2.995', 'learning_rate': '1.175e-05', 'epoch': '1.342'}
{'loss': '0.4548', 'grad_norm': '4.617', 'learning_rate': '1.164e-05', 'epoch': '1.385'}
{'loss': '0.3719', 'grad_norm': '1.867', 'learning_rate': '1.153e-05', 'epoch': '1.429'}
{'loss': '0.465', 'grad_norm': '14.33', 'learning_rate': '1.142e-05', 'epoch': '1.472'}
{'loss': '0.39', 'grad_norm': '28.84', 'learning_rate': '1.132e-05', 'epoch': '1.515'}
{'loss': '0.4656', 'grad_norm': '5.568', 'learning_rate': '1.121e-05', 'epoch': '1.558'}
{'loss': '0.3818', 'grad_norm': '11.75', 'learning_rate': '1.11e-05', 'epoch': '1.602'}
{'loss': '0.5103', 'grad_norm': '0.9849', 'learning_rate': '1.099e-05', 'epoch': '1.645'}
{'loss': '0.4702', 'grad_norm': '4.35', 'learning_rate': '1.088e-05', 'epoch': '1.688'}
{'loss': '0.4781', 'grad_norm': '1.759', 'learning_rate': '1.077e-05', 'epoch': '1.732'}
{'loss': '0.4941', 'grad_norm': '22.45', 'learning_rate': '1.066e-05', 'epoch': '1.775'}
{'loss': '0.4957', 'grad_norm': '17.2', 'learning_rate': '1.055e-05', 'epoch': '1.818'}
{'loss': '0.4574', 'grad_norm': '20.23', 'learning_rate': '1.044e-05', 'epoch': '1.861'}
{'loss': '0.4917', 'grad_norm': '1.989', 'learning_rate': '1.033e-05', 'epoch': '1.905'}
{'loss': '0.3706', 'grad_norm': '5.966', 'learning_rate': '1.022e-05', 'epoch': '1.948'}
{'loss': '0.4787', 'grad_norm': '5.625', 'learning_rate': '1.011e-05', 'epoch': '1.991'}
{'eval_loss': '0.6979', 'eval_accuracy': '0.906', 'eval_f1': '0.5156', 'eval_recall': '0.55', 'eval_precision': '0.4853', 'eval_roc_auc': '0.7458', 'eval_runtime': '13.34', 'eval_samples_per_second': '197.7', 'eval_steps_per_second': '6.221', 'epoch': '2'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.2408', 'grad_norm': '32.19', 'learning_rate': '1e-05', 'epoch': '2.035'}
{'loss': '0.4266', 'grad_norm': '50.34', 'learning_rate': '9.896e-06', 'epoch': '2.078'}
{'loss': '0.2882', 'grad_norm': '3.526', 'learning_rate': '9.786e-06', 'epoch': '2.121'}
{'loss': '0.3106', 'grad_norm': '12.76', 'learning_rate': '9.677e-06', 'epoch': '2.165'}
{'loss': '0.2982', 'grad_norm': '1.215', 'learning_rate': '9.568e-06', 'epoch': '2.208'}
{'loss': '0.355', 'grad_norm': '12.8', 'learning_rate': '9.459e-06', 'epoch': '2.251'}
{'loss': '0.3327', 'grad_norm': '0.2643', 'learning_rate': '9.35e-06', 'epoch': '2.294'}
{'loss': '0.3494', 'grad_norm': '61.1', 'learning_rate': '9.24e-06', 'epoch': '2.338'}
{'loss': '0.3956', 'grad_norm': '2.374', 'learning_rate': '9.131e-06', 'epoch': '2.381'}
{'loss': '0.3694', 'grad_norm': '65.15', 'learning_rate': '9.022e-06', 'epoch': '2.424'}
{'loss': '0.3436', 'grad_norm': '10.06', 'learning_rate': '8.913e-06', 'epoch': '2.468'}
{'loss': '0.3736', 'grad_norm': '5.25', 'learning_rate': '8.804e-06', 'epoch': '2.511'}
{'loss': '0.3937', 'grad_norm': '18.66', 'learning_rate': '8.694e-06', 'epoch': '2.554'}
{'loss': '0.3627', 'grad_norm': '20.74', 'learning_rate': '8.585e-06', 'epoch': '2.597'}
{'loss': '0.2569', 'grad_norm': '54.75', 'learning_rate': '8.476e-06', 'epoch': '2.641'}
{'loss': '0.3385', 'grad_norm': '8.36', 'learning_rate': '8.367e-06', 'epoch': '2.684'}
{'loss': '0.3743', 'grad_norm': '2.968', 'learning_rate': '8.258e-06', 'epoch': '2.727'}
{'loss': '0.3381', 'grad_norm': '4.165', 'learning_rate': '8.148e-06', 'epoch': '2.771'}
{'loss': '0.4093', 'grad_norm': '26.75', 'learning_rate': '8.039e-06', 'epoch': '2.814'}
{'loss': '0.4021', 'grad_norm': '16.43', 'learning_rate': '7.93e-06', 'epoch': '2.857'}
{'loss': '0.4427', 'grad_norm': '7.843', 'learning_rate': '7.821e-06', 'epoch': '2.9'}
{'loss': '0.3138', 'grad_norm': '20.91', 'learning_rate': '7.712e-06', 'epoch': '2.944'}
{'loss': '0.503', 'grad_norm': '56.42', 'learning_rate': '7.602e-06', 'epoch': '2.987'}
{'eval_loss': '0.773', 'eval_accuracy': '0.8867', 'eval_f1': '0.4924', 'eval_recall': '0.6042', 'eval_precision': '0.4155', 'eval_roc_auc': '0.7595', 'eval_runtime': '13.32', 'eval_samples_per_second': '198.1', 'eval_steps_per_second': '6.231', 'epoch': '3'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.2862', 'grad_norm': '64.99', 'learning_rate': '7.493e-06', 'epoch': '3.03'}
{'loss': '0.1533', 'grad_norm': '53.98', 'learning_rate': '7.384e-06', 'epoch': '3.074'}
{'loss': '0.2545', 'grad_norm': '5.813', 'learning_rate': '7.275e-06', 'epoch': '3.117'}
{'loss': '0.2524', 'grad_norm': '5.154', 'learning_rate': '7.166e-06', 'epoch': '3.16'}
{'loss': '0.1702', 'grad_norm': '3.886', 'learning_rate': '7.056e-06', 'epoch': '3.203'}
{'loss': '0.3927', 'grad_norm': '3.409', 'learning_rate': '6.947e-06', 'epoch': '3.247'}
{'loss': '0.1989', 'grad_norm': '7.104', 'learning_rate': '6.838e-06', 'epoch': '3.29'}
{'loss': '0.2455', 'grad_norm': '84.38', 'learning_rate': '6.729e-06', 'epoch': '3.333'}
{'loss': '0.3045', 'grad_norm': '82.43', 'learning_rate': '6.62e-06', 'epoch': '3.377'}
{'loss': '0.2277', 'grad_norm': '0.2339', 'learning_rate': '6.51e-06', 'epoch': '3.42'}
{'loss': '0.2103', 'grad_norm': '1.203', 'learning_rate': '6.401e-06', 'epoch': '3.463'}
{'loss': '0.2203', 'grad_norm': '0.471', 'learning_rate': '6.292e-06', 'epoch': '3.506'}
{'loss': '0.3716', 'grad_norm': '31.72', 'learning_rate': '6.183e-06', 'epoch': '3.55'}
{'loss': '0.2586', 'grad_norm': '14.76', 'learning_rate': '6.074e-06', 'epoch': '3.593'}
{'loss': '0.34', 'grad_norm': '22.89', 'learning_rate': '5.964e-06', 'epoch': '3.636'}
{'loss': '0.1886', 'grad_norm': '0.1357', 'learning_rate': '5.855e-06', 'epoch': '3.68'}
{'loss': '0.3524', 'grad_norm': '1.505', 'learning_rate': '5.746e-06', 'epoch': '3.723'}
{'loss': '0.2116', 'grad_norm': '0.5586', 'learning_rate': '5.637e-06', 'epoch': '3.766'}
{'loss': '0.3404', 'grad_norm': '18.26', 'learning_rate': '5.528e-06', 'epoch': '3.81'}
{'loss': '0.3425', 'grad_norm': '0.5359', 'learning_rate': '5.418e-06', 'epoch': '3.853'}
{'loss': '0.2835', 'grad_norm': '69.41', 'learning_rate': '5.309e-06', 'epoch': '3.896'}
{'loss': '0.267', 'grad_norm': '17.81', 'learning_rate': '5.2e-06', 'epoch': '3.939'}
{'loss': '0.1912', 'grad_norm': '7.259', 'learning_rate': '5.091e-06', 'epoch': '3.983'}
{'eval_loss': '1.588', 'eval_accuracy': '0.9052', 'eval_f1': '0.4369', 'eval_recall': '0.4042', 'eval_precision': '0.4755', 'eval_roc_auc': '0.6798', 'eval_runtime': '13.33', 'eval_samples_per_second': '197.9', 'eval_steps_per_second': '6.226', 'epoch': '4'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'train_runtime': '1388', 'train_samples_per_second': '79.8', 'train_steps_per_second': '4.992', 'train_loss': '0.3962', 'epoch': '4'}

[I 2026-09-22 09:08:50,290] Trial 1 finished with value: 0.5147347740667977 and parameters: {'learning_rate': 1.5135080908039024e-05, 'num_train_epochs': 6, 'per_device_train_batch_size': 8, 'weight_decay': 0.08163317323853851}. Best is trial 1 with value: 0.5147347740667977.

{'eval_loss': '0.7037', 'eval_accuracy': '0.9064', 'eval_f1': '0.5147', 'eval_recall': '0.5458', 'eval_precision': '0.487', 'eval_roc_auc': '0.7441', 'eval_runtime': '13.32', 'eval_samples_per_second': '198.1', 'eval_steps_per_second': '6.232', 'epoch': '4'}

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

{'loss': '0.7168', 'grad_norm': '11.97', 'learning_rate': '4.318e-05', 'epoch': '0.04329'}
{'loss': '0.5717', 'grad_norm': '22.19', 'learning_rate': '4.286e-05', 'epoch': '0.08658'}
{'loss': '0.611', 'grad_norm': '3.622', 'learning_rate': '4.255e-05', 'epoch': '0.1299'}
{'loss': '0.5995', 'grad_norm': '9.681', 'learning_rate': '4.224e-05', 'epoch': '0.1732'}
{'loss': '0.6302', 'grad_norm': '9.862', 'learning_rate': '4.192e-05', 'epoch': '0.2165'}
{'loss': '0.6364', 'grad_norm': '7.339', 'learning_rate': '4.161e-05', 'epoch': '0.2597'}
{'loss': '0.678', 'grad_norm': '10.99', 'learning_rate': '4.129e-05', 'epoch': '0.303'}
{'loss': '0.683', 'grad_norm': '4.806', 'learning_rate': '4.098e-05', 'epoch': '0.3463'}
{'loss': '0.4922', 'grad_norm': '16.05', 'learning_rate': '4.067e-05', 'epoch': '0.3896'}
{'loss': '0.6416', 'grad_norm': '2.662', 'learning_rate': '4.035e-05', 'epoch': '0.4329'}
{'loss': '0.7527', 'grad_norm': '2.563', 'learning_rate': '4.004e-05', 'epoch': '0.4762'}
{'loss': '0.5706', 'grad_norm': '4.064', 'learning_rate': '3.973e-05', 'epoch': '0.5195'}
{'loss': '0.5277', 'grad_norm': '4.08', 'learning_rate': '3.941e-05', 'epoch': '0.5628'}
{'loss': '0.5106', 'grad_norm': '3.885', 'learning_rate': '3.91e-05', 'epoch': '0.6061'}
{'loss': '0.617', 'grad_norm': '8.249', 'learning_rate': '3.878e-05', 'epoch': '0.6494'}
{'loss': '0.5523', 'grad_norm': '2.265', 'learning_rate': '3.847e-05', 'epoch': '0.6926'}
{'loss': '0.4886', 'grad_norm': '3.641', 'learning_rate': '3.816e-05', 'epoch': '0.7359'}
{'loss': '0.6644', 'grad_norm': '9.904', 'learning_rate': '3.784e-05', 'epoch': '0.7792'}
{'loss': '0.5627', 'grad_norm': '17.81', 'learning_rate': '3.753e-05', 'epoch': '0.8225'}
{'loss': '0.5132', 'grad_norm': '22.94', 'learning_rate': '3.722e-05', 'epoch': '0.8658'}
{'loss': '0.4798', 'grad_norm': '12.88', 'learning_rate': '3.69e-05', 'epoch': '0.9091'}
{'loss': '0.5954', 'grad_norm': '10.89', 'learning_rate': '3.659e-05', 'epoch': '0.9524'}
{'loss': '0.6367', 'grad_norm': '6.122', 'learning_rate': '3.627e-05', 'epoch': '0.9957'}
{'eval_loss': '0.4688', 'eval_accuracy': '0.8563', 'eval_f1': '0.4844', 'eval_recall': '0.7417', 'eval_precision': '0.3596', 'eval_roc_auc': '0.8047', 'eval_runtime': '13.35', 'eval_samples_per_second': '197.6', 'eval_steps_per_second': '6.219', 'epoch': '1'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.4406', 'grad_norm': '80.5', 'learning_rate': '3.596e-05', 'epoch': '1.039'}
{'loss': '0.5175', 'grad_norm': '8.774', 'learning_rate': '3.565e-05', 'epoch': '1.082'}
{'loss': '0.4096', 'grad_norm': '3.774', 'learning_rate': '3.533e-05', 'epoch': '1.126'}
{'loss': '0.3723', 'grad_norm': '2.847', 'learning_rate': '3.502e-05', 'epoch': '1.169'}
{'loss': '0.5068', 'grad_norm': '6.143', 'learning_rate': '3.471e-05', 'epoch': '1.212'}
{'loss': '0.4341', 'grad_norm': '4.922', 'learning_rate': '3.439e-05', 'epoch': '1.255'}
{'loss': '0.5401', 'grad_norm': '12.21', 'learning_rate': '3.408e-05', 'epoch': '1.299'}
{'loss': '0.4392', 'grad_norm': '1.23', 'learning_rate': '3.376e-05', 'epoch': '1.342'}
{'loss': '0.4844', 'grad_norm': '1.797', 'learning_rate': '3.345e-05', 'epoch': '1.385'}
{'loss': '0.3666', 'grad_norm': '2.263', 'learning_rate': '3.314e-05', 'epoch': '1.429'}
{'loss': '0.5721', 'grad_norm': '10.54', 'learning_rate': '3.282e-05', 'epoch': '1.472'}
{'loss': '0.4264', 'grad_norm': '15.01', 'learning_rate': '3.251e-05', 'epoch': '1.515'}
{'loss': '0.4473', 'grad_norm': '3.905', 'learning_rate': '3.22e-05', 'epoch': '1.558'}
{'loss': '0.3789', 'grad_norm': '6.343', 'learning_rate': '3.188e-05', 'epoch': '1.602'}
{'loss': '0.487', 'grad_norm': '1.499', 'learning_rate': '3.157e-05', 'epoch': '1.645'}
{'loss': '0.5637', 'grad_norm': '0.8324', 'learning_rate': '3.125e-05', 'epoch': '1.688'}
{'loss': '0.4687', 'grad_norm': '0.9492', 'learning_rate': '3.094e-05', 'epoch': '1.732'}
{'loss': '0.4924', 'grad_norm': '22.62', 'learning_rate': '3.063e-05', 'epoch': '1.775'}
{'loss': '0.578', 'grad_norm': '16.82', 'learning_rate': '3.031e-05', 'epoch': '1.818'}
{'loss': '0.5038', 'grad_norm': '16.01', 'learning_rate': '3e-05', 'epoch': '1.861'}
{'loss': '0.5151', 'grad_norm': '7.7', 'learning_rate': '2.969e-05', 'epoch': '1.905'}
{'loss': '0.3485', 'grad_norm': '5.493', 'learning_rate': '2.937e-05', 'epoch': '1.948'}
{'loss': '0.6176', 'grad_norm': '3.8', 'learning_rate': '2.906e-05', 'epoch': '1.991'}
{'eval_loss': '0.6189', 'eval_accuracy': '0.898', 'eval_f1': '0.5082', 'eval_recall': '0.5792', 'eval_precision': '0.4528', 'eval_roc_auc': '0.7546', 'eval_runtime': '13.39', 'eval_samples_per_second': '197.1', 'eval_steps_per_second': '6.201', 'epoch': '2'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.278', 'grad_norm': '13.66', 'learning_rate': '2.874e-05', 'epoch': '2.035'}
{'loss': '0.3363', 'grad_norm': '46.95', 'learning_rate': '2.843e-05', 'epoch': '2.078'}
{'loss': '0.2954', 'grad_norm': '22.69', 'learning_rate': '2.812e-05', 'epoch': '2.121'}
{'loss': '0.2827', 'grad_norm': '43.4', 'learning_rate': '2.78e-05', 'epoch': '2.165'}
{'loss': '0.2605', 'grad_norm': '0.08942', 'learning_rate': '2.749e-05', 'epoch': '2.208'}
{'loss': '0.3011', 'grad_norm': '48.13', 'learning_rate': '2.718e-05', 'epoch': '2.251'}
{'loss': '0.3444', 'grad_norm': '0.0985', 'learning_rate': '2.686e-05', 'epoch': '2.294'}
{'loss': '0.348', 'grad_norm': '20.48', 'learning_rate': '2.655e-05', 'epoch': '2.338'}
{'loss': '0.3409', 'grad_norm': '2.178', 'learning_rate': '2.624e-05', 'epoch': '2.381'}
{'loss': '0.3234', 'grad_norm': '0.464', 'learning_rate': '2.592e-05', 'epoch': '2.424'}
{'loss': '0.2874', 'grad_norm': '2.274', 'learning_rate': '2.561e-05', 'epoch': '2.468'}
{'loss': '0.3969', 'grad_norm': '7.692', 'learning_rate': '2.529e-05', 'epoch': '2.511'}
{'loss': '0.3628', 'grad_norm': '12.51', 'learning_rate': '2.498e-05', 'epoch': '2.554'}
{'loss': '0.3068', 'grad_norm': '0.3023', 'learning_rate': '2.467e-05', 'epoch': '2.597'}
{'loss': '0.2738', 'grad_norm': '53.07', 'learning_rate': '2.435e-05', 'epoch': '2.641'}
{'loss': '0.3424', 'grad_norm': '4.286', 'learning_rate': '2.404e-05', 'epoch': '2.684'}
{'loss': '0.4046', 'grad_norm': '1.97', 'learning_rate': '2.373e-05', 'epoch': '2.727'}
{'loss': '0.3629', 'grad_norm': '2.096', 'learning_rate': '2.341e-05', 'epoch': '2.771'}
{'loss': '0.4299', 'grad_norm': '23.62', 'learning_rate': '2.31e-05', 'epoch': '2.814'}
{'loss': '0.3749', 'grad_norm': '18.06', 'learning_rate': '2.278e-05', 'epoch': '2.857'}
{'loss': '0.4006', 'grad_norm': '1.87', 'learning_rate': '2.247e-05', 'epoch': '2.9'}
{'loss': '0.3616', 'grad_norm': '17.17', 'learning_rate': '2.216e-05', 'epoch': '2.944'}
{'loss': '0.5113', 'grad_norm': '31.05', 'learning_rate': '2.184e-05', 'epoch': '2.987'}
{'eval_loss': '0.7595', 'eval_accuracy': '0.8848', 'eval_f1': '0.4759', 'eval_recall': '0.575', 'eval_precision': '0.4059', 'eval_roc_auc': '0.7454', 'eval_runtime': '13.37', 'eval_samples_per_second': '197.3', 'eval_steps_per_second': '6.208', 'epoch': '3'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.2223', 'grad_norm': '61.44', 'learning_rate': '2.153e-05', 'epoch': '3.03'}
{'loss': '0.2459', 'grad_norm': '31.3', 'learning_rate': '2.122e-05', 'epoch': '3.074'}
{'loss': '0.1593', 'grad_norm': '87.3', 'learning_rate': '2.09e-05', 'epoch': '3.117'}
{'loss': '0.1955', 'grad_norm': '8.838', 'learning_rate': '2.059e-05', 'epoch': '3.16'}
{'loss': '0.2441', 'grad_norm': '1.403', 'learning_rate': '2.027e-05', 'epoch': '3.203'}
{'loss': '0.2189', 'grad_norm': '11.07', 'learning_rate': '1.996e-05', 'epoch': '3.247'}
{'loss': '0.1248', 'grad_norm': '0.02274', 'learning_rate': '1.965e-05', 'epoch': '3.29'}
{'loss': '0.2177', 'grad_norm': '48.11', 'learning_rate': '1.933e-05', 'epoch': '3.333'}
{'loss': '0.2627', 'grad_norm': '0.579', 'learning_rate': '1.902e-05', 'epoch': '3.377'}
{'loss': '0.2348', 'grad_norm': '0.09264', 'learning_rate': '1.871e-05', 'epoch': '3.42'}
{'loss': '0.1729', 'grad_norm': '0.06801', 'learning_rate': '1.839e-05', 'epoch': '3.463'}
{'loss': '0.1736', 'grad_norm': '0.07876', 'learning_rate': '1.808e-05', 'epoch': '3.506'}
{'loss': '0.2567', 'grad_norm': '112.7', 'learning_rate': '1.776e-05', 'epoch': '3.55'}
{'loss': '0.3249', 'grad_norm': '87.37', 'learning_rate': '1.745e-05', 'epoch': '3.593'}
{'loss': '0.2044', 'grad_norm': '56.35', 'learning_rate': '1.714e-05', 'epoch': '3.636'}
{'loss': '0.2454', 'grad_norm': '0.1085', 'learning_rate': '1.682e-05', 'epoch': '3.68'}
{'loss': '0.2967', 'grad_norm': '158.1', 'learning_rate': '1.651e-05', 'epoch': '3.723'}
{'loss': '0.142', 'grad_norm': '0.2416', 'learning_rate': '1.62e-05', 'epoch': '3.766'}
{'loss': '0.2162', 'grad_norm': '1.995', 'learning_rate': '1.588e-05', 'epoch': '3.81'}
{'loss': '0.1709', 'grad_norm': '0.06384', 'learning_rate': '1.557e-05', 'epoch': '3.853'}
{'loss': '0.1848', 'grad_norm': '4.104', 'learning_rate': '1.525e-05', 'epoch': '3.896'}
{'loss': '0.1497', 'grad_norm': '13.28', 'learning_rate': '1.494e-05', 'epoch': '3.939'}
{'loss': '0.2492', 'grad_norm': '105.4', 'learning_rate': '1.463e-05', 'epoch': '3.983'}
{'eval_loss': '1.683', 'eval_accuracy': '0.9064', 'eval_f1': '0.4296', 'eval_recall': '0.3875', 'eval_precision': '0.4819', 'eval_roc_auc': '0.6729', 'eval_runtime': '13.35', 'eval_samples_per_second': '197.5', 'eval_steps_per_second': '6.215', 'epoch': '4'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'train_runtime': '1387', 'train_samples_per_second': '79.89', 'train_steps_per_second': '4.997', 'train_loss': '0.4064', 'epoch': '4'}

[I 2026-09-22 09:32:14,224] Trial 2 finished with value: 0.5054945054945055 and parameters: {'learning_rate': 4.3484547073648765e-05, 'num_train_epochs': 6, 'per_device_train_batch_size': 8, 'weight_decay': 0.03355142206244837}. Best is trial 1 with value: 0.5147347740667977.

{'eval_loss': '0.6252', 'eval_accuracy': '0.8976', 'eval_f1': '0.5055', 'eval_recall': '0.575', 'eval_precision': '0.451', 'eval_roc_auc': '0.7525', 'eval_runtime': '13.33', 'eval_samples_per_second': '197.9', 'eval_steps_per_second': '6.227', 'epoch': '4'}

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

{'loss': '0.6936', 'grad_norm': '11.61', 'learning_rate': '2.66e-05', 'epoch': '0.04329'}
{'loss': '0.533', 'grad_norm': '15.5', 'learning_rate': '2.641e-05', 'epoch': '0.08658'}
{'loss': '0.5654', 'grad_norm': '4.215', 'learning_rate': '2.621e-05', 'epoch': '0.1299'}
{'loss': '0.5511', 'grad_norm': '17', 'learning_rate': '2.602e-05', 'epoch': '0.1732'}
{'loss': '0.5266', 'grad_norm': '28.01', 'learning_rate': '2.583e-05', 'epoch': '0.2165'}
{'loss': '0.6655', 'grad_norm': '3.903', 'learning_rate': '2.563e-05', 'epoch': '0.2597'}
{'loss': '0.6609', 'grad_norm': '10.37', 'learning_rate': '2.544e-05', 'epoch': '0.303'}
{'loss': '0.6286', 'grad_norm': '3.71', 'learning_rate': '2.525e-05', 'epoch': '0.3463'}
{'loss': '0.4944', 'grad_norm': '9.19', 'learning_rate': '2.505e-05', 'epoch': '0.3896'}
{'loss': '0.5875', 'grad_norm': '6.348', 'learning_rate': '2.486e-05', 'epoch': '0.4329'}
{'loss': '0.6629', 'grad_norm': '4.07', 'learning_rate': '2.467e-05', 'epoch': '0.4762'}
{'loss': '0.5478', 'grad_norm': '7.021', 'learning_rate': '2.447e-05', 'epoch': '0.5195'}
{'loss': '0.4907', 'grad_norm': '2.84', 'learning_rate': '2.428e-05', 'epoch': '0.5628'}
{'loss': '0.5018', 'grad_norm': '3.73', 'learning_rate': '2.409e-05', 'epoch': '0.6061'}
{'loss': '0.5698', 'grad_norm': '6.544', 'learning_rate': '2.389e-05', 'epoch': '0.6494'}
{'loss': '0.4914', 'grad_norm': '4.569', 'learning_rate': '2.37e-05', 'epoch': '0.6926'}
{'loss': '0.5022', 'grad_norm': '7.426', 'learning_rate': '2.351e-05', 'epoch': '0.7359'}
{'loss': '0.6131', 'grad_norm': '51.64', 'learning_rate': '2.331e-05', 'epoch': '0.7792'}
{'loss': '0.5299', 'grad_norm': '13.14', 'learning_rate': '2.312e-05', 'epoch': '0.8225'}
{'loss': '0.5028', 'grad_norm': '7.633', 'learning_rate': '2.293e-05', 'epoch': '0.8658'}
{'loss': '0.49', 'grad_norm': '10.54', 'learning_rate': '2.273e-05', 'epoch': '0.9091'}
{'loss': '0.546', 'grad_norm': '15.45', 'learning_rate': '2.254e-05', 'epoch': '0.9524'}
{'loss': '0.6271', 'grad_norm': '6.361', 'learning_rate': '2.235e-05', 'epoch': '0.9957'}
{'eval_loss': '0.4737', 'eval_accuracy': '0.8567', 'eval_f1': '0.4721', 'eval_recall': '0.7042', 'eval_precision': '0.355', 'eval_roc_auc': '0.7881', 'eval_runtime': '13.35', 'eval_samples_per_second': '197.6', 'eval_steps_per_second': '6.218', 'epoch': '1'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.4068', 'grad_norm': '39.93', 'learning_rate': '2.215e-05', 'epoch': '1.039'}
{'loss': '0.5054', 'grad_norm': '3.205', 'learning_rate': '2.196e-05', 'epoch': '1.082'}
{'loss': '0.3943', 'grad_norm': '7.782', 'learning_rate': '2.177e-05', 'epoch': '1.126'}
{'loss': '0.3772', 'grad_norm': '2.23', 'learning_rate': '2.157e-05', 'epoch': '1.169'}
{'loss': '0.4756', 'grad_norm': '6.149', 'learning_rate': '2.138e-05', 'epoch': '1.212'}
{'loss': '0.4208', 'grad_norm': '7.677', 'learning_rate': '2.119e-05', 'epoch': '1.255'}
{'loss': '0.5079', 'grad_norm': '30.57', 'learning_rate': '2.099e-05', 'epoch': '1.299'}
{'loss': '0.4373', 'grad_norm': '2.21', 'learning_rate': '2.08e-05', 'epoch': '1.342'}
{'loss': '0.4627', 'grad_norm': '2.717', 'learning_rate': '2.061e-05', 'epoch': '1.385'}
{'loss': '0.3745', 'grad_norm': '8.042', 'learning_rate': '2.041e-05', 'epoch': '1.429'}
{'loss': '0.4658', 'grad_norm': '13.31', 'learning_rate': '2.022e-05', 'epoch': '1.472'}
{'loss': '0.4393', 'grad_norm': '23.66', 'learning_rate': '2.003e-05', 'epoch': '1.515'}
{'loss': '0.4392', 'grad_norm': '4.183', 'learning_rate': '1.984e-05', 'epoch': '1.558'}
{'loss': '0.3824', 'grad_norm': '9.801', 'learning_rate': '1.964e-05', 'epoch': '1.602'}
{'loss': '0.5026', 'grad_norm': '1.392', 'learning_rate': '1.945e-05', 'epoch': '1.645'}
{'loss': '0.4352', 'grad_norm': '2.981', 'learning_rate': '1.926e-05', 'epoch': '1.688'}
{'loss': '0.4838', 'grad_norm': '0.9557', 'learning_rate': '1.906e-05', 'epoch': '1.732'}
{'loss': '0.4762', 'grad_norm': '80.49', 'learning_rate': '1.887e-05', 'epoch': '1.775'}
{'loss': '0.5305', 'grad_norm': '6.72', 'learning_rate': '1.868e-05', 'epoch': '1.818'}
{'loss': '0.4757', 'grad_norm': '13.94', 'learning_rate': '1.848e-05', 'epoch': '1.861'}
{'loss': '0.4821', 'grad_norm': '0.8126', 'learning_rate': '1.829e-05', 'epoch': '1.905'}
{'loss': '0.3992', 'grad_norm': '5.323', 'learning_rate': '1.81e-05', 'epoch': '1.948'}
{'loss': '0.5034', 'grad_norm': '4.241', 'learning_rate': '1.79e-05', 'epoch': '1.991'}
{'eval_loss': '0.669', 'eval_accuracy': '0.8984', 'eval_f1': '0.5055', 'eval_recall': '0.5708', 'eval_precision': '0.4536', 'eval_roc_auc': '0.751', 'eval_runtime': '13.42', 'eval_samples_per_second': '196.6', 'eval_steps_per_second': '6.185', 'epoch': '2'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.2257', 'grad_norm': '9.081', 'learning_rate': '1.771e-05', 'epoch': '2.035'}
{'loss': '0.3255', 'grad_norm': '65.94', 'learning_rate': '1.752e-05', 'epoch': '2.078'}
{'loss': '0.2772', 'grad_norm': '55.57', 'learning_rate': '1.732e-05', 'epoch': '2.121'}
{'loss': '0.2909', 'grad_norm': '8.42', 'learning_rate': '1.713e-05', 'epoch': '2.165'}
{'loss': '0.2806', 'grad_norm': '0.1724', 'learning_rate': '1.694e-05', 'epoch': '2.208'}
{'loss': '0.3055', 'grad_norm': '5.685', 'learning_rate': '1.674e-05', 'epoch': '2.251'}
{'loss': '0.3071', 'grad_norm': '0.1134', 'learning_rate': '1.655e-05', 'epoch': '2.294'}
{'loss': '0.3269', 'grad_norm': '14.98', 'learning_rate': '1.636e-05', 'epoch': '2.338'}
{'loss': '0.3547', 'grad_norm': '0.9083', 'learning_rate': '1.616e-05', 'epoch': '2.381'}
{'loss': '0.3095', 'grad_norm': '0.3552', 'learning_rate': '1.597e-05', 'epoch': '2.424'}
{'loss': '0.3194', 'grad_norm': '1.2', 'learning_rate': '1.578e-05', 'epoch': '2.468'}
{'loss': '0.3747', 'grad_norm': '6.077', 'learning_rate': '1.558e-05', 'epoch': '2.511'}
{'loss': '0.3145', 'grad_norm': '23.22', 'learning_rate': '1.539e-05', 'epoch': '2.554'}
{'loss': '0.3902', 'grad_norm': '5.639', 'learning_rate': '1.52e-05', 'epoch': '2.597'}
{'loss': '0.2955', 'grad_norm': '74.85', 'learning_rate': '1.5e-05', 'epoch': '2.641'}
{'loss': '0.3296', 'grad_norm': '5.058', 'learning_rate': '1.481e-05', 'epoch': '2.684'}
{'loss': '0.3793', 'grad_norm': '9.469', 'learning_rate': '1.462e-05', 'epoch': '2.727'}
{'loss': '0.2549', 'grad_norm': '3.115', 'learning_rate': '1.442e-05', 'epoch': '2.771'}
{'loss': '0.4064', 'grad_norm': '28.99', 'learning_rate': '1.423e-05', 'epoch': '2.814'}
{'loss': '0.4417', 'grad_norm': '10.14', 'learning_rate': '1.404e-05', 'epoch': '2.857'}
{'loss': '0.3777', 'grad_norm': '1.246', 'learning_rate': '1.384e-05', 'epoch': '2.9'}
{'loss': '0.2969', 'grad_norm': '22.75', 'learning_rate': '1.365e-05', 'epoch': '2.944'}
{'loss': '0.3686', 'grad_norm': '53.53', 'learning_rate': '1.346e-05', 'epoch': '2.987'}
{'eval_loss': '0.9059', 'eval_accuracy': '0.8965', 'eval_f1': '0.4897', 'eval_recall': '0.5458', 'eval_precision': '0.4441', 'eval_roc_auc': '0.7387', 'eval_runtime': '13.4', 'eval_samples_per_second': '196.8', 'eval_steps_per_second': '6.193', 'epoch': '3'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.2185', 'grad_norm': '63.77', 'learning_rate': '1.326e-05', 'epoch': '3.03'}
{'loss': '0.2092', 'grad_norm': '47.23', 'learning_rate': '1.307e-05', 'epoch': '3.074'}
{'loss': '0.2285', 'grad_norm': '6.893', 'learning_rate': '1.288e-05', 'epoch': '3.117'}
{'loss': '0.1719', 'grad_norm': '4.144', 'learning_rate': '1.268e-05', 'epoch': '3.16'}
{'loss': '0.1775', 'grad_norm': '4.638', 'learning_rate': '1.249e-05', 'epoch': '3.203'}
{'loss': '0.3018', 'grad_norm': '0.9979', 'learning_rate': '1.23e-05', 'epoch': '3.247'}
{'loss': '0.1527', 'grad_norm': '0.08658', 'learning_rate': '1.21e-05', 'epoch': '3.29'}
{'loss': '0.1642', 'grad_norm': '14.52', 'learning_rate': '1.191e-05', 'epoch': '3.333'}
{'loss': '0.2744', 'grad_norm': '35.52', 'learning_rate': '1.172e-05', 'epoch': '3.377'}
{'loss': '0.1697', 'grad_norm': '0.08272', 'learning_rate': '1.152e-05', 'epoch': '3.42'}
{'loss': '0.1591', 'grad_norm': '0.1801', 'learning_rate': '1.133e-05', 'epoch': '3.463'}
{'loss': '0.163', 'grad_norm': '0.05749', 'learning_rate': '1.114e-05', 'epoch': '3.506'}
{'loss': '0.2508', 'grad_norm': '62.2', 'learning_rate': '1.094e-05', 'epoch': '3.55'}
{'loss': '0.1987', 'grad_norm': '95.56', 'learning_rate': '1.075e-05', 'epoch': '3.593'}
{'loss': '0.2305', 'grad_norm': '82.31', 'learning_rate': '1.056e-05', 'epoch': '3.636'}
{'loss': '0.1584', 'grad_norm': '0.1189', 'learning_rate': '1.036e-05', 'epoch': '3.68'}
{'loss': '0.2744', 'grad_norm': '0.0661', 'learning_rate': '1.017e-05', 'epoch': '3.723'}
{'loss': '0.1632', 'grad_norm': '0.0243', 'learning_rate': '9.977e-06', 'epoch': '3.766'}
{'loss': '0.2285', 'grad_norm': '19.4', 'learning_rate': '9.784e-06', 'epoch': '3.81'}
{'loss': '0.2244', 'grad_norm': '0.08193', 'learning_rate': '9.591e-06', 'epoch': '3.853'}
{'loss': '0.1601', 'grad_norm': '12.15', 'learning_rate': '9.398e-06', 'epoch': '3.896'}
{'loss': '0.1449', 'grad_norm': '3.23', 'learning_rate': '9.204e-06', 'epoch': '3.939'}
{'loss': '0.2024', 'grad_norm': '9.358', 'learning_rate': '9.011e-06', 'epoch': '3.983'}
{'eval_loss': '1.727', 'eval_accuracy': '0.9037', 'eval_f1': '0.4573', 'eval_recall': '0.4458', 'eval_precision': '0.4693', 'eval_roc_auc': '0.6977', 'eval_runtime': '13.39', 'eval_samples_per_second': '197.1', 'eval_steps_per_second': '6.2', 'epoch': '4'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'train_runtime': '1389', 'train_samples_per_second': '79.75', 'train_steps_per_second': '4.988', 'train_loss': '0.3852', 'epoch': '4'}

[I 2026-09-22 09:55:40,245] Trial 3 finished with value: 0.5074074074074074 and parameters: {'learning_rate': 2.678945251968088e-05, 'num_train_epochs': 6, 'per_device_train_batch_size': 8, 'weight_decay': 0.09738042175441157}. Best is trial 1 with value: 0.5147347740667977.

{'eval_loss': '0.6737', 'eval_accuracy': '0.8992', 'eval_f1': '0.5074', 'eval_recall': '0.5708', 'eval_precision': '0.4567', 'eval_roc_auc': '0.7514', 'eval_runtime': '13.33', 'eval_samples_per_second': '197.9', 'eval_steps_per_second': '6.226', 'epoch': '4'}

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

{'loss': '0.6995', 'grad_norm': '11.61', 'learning_rate': '3.287e-05', 'epoch': '0.04329'}
{'loss': '0.5414', 'grad_norm': '16.3', 'learning_rate': '3.238e-05', 'epoch': '0.08658'}
{'loss': '0.5646', 'grad_norm': '10.76', 'learning_rate': '3.19e-05', 'epoch': '0.1299'}
{'loss': '0.6159', 'grad_norm': '10.38', 'learning_rate': '3.142e-05', 'epoch': '0.1732'}
{'loss': '0.5694', 'grad_norm': '9.12', 'learning_rate': '3.094e-05', 'epoch': '0.2165'}
{'loss': '0.6672', 'grad_norm': '4.345', 'learning_rate': '3.046e-05', 'epoch': '0.2597'}
{'loss': '0.6794', 'grad_norm': '8.732', 'learning_rate': '2.998e-05', 'epoch': '0.303'}
{'loss': '0.6127', 'grad_norm': '3.414', 'learning_rate': '2.95e-05', 'epoch': '0.3463'}
{'loss': '0.4933', 'grad_norm': '11.12', 'learning_rate': '2.902e-05', 'epoch': '0.3896'}
{'loss': '0.5823', 'grad_norm': '5.611', 'learning_rate': '2.854e-05', 'epoch': '0.4329'}
{'loss': '0.6908', 'grad_norm': '4.854', 'learning_rate': '2.806e-05', 'epoch': '0.4762'}
{'loss': '0.5807', 'grad_norm': '8.762', 'learning_rate': '2.757e-05', 'epoch': '0.5195'}
{'loss': '0.4889', 'grad_norm': '3.553', 'learning_rate': '2.709e-05', 'epoch': '0.5628'}
{'loss': '0.5113', 'grad_norm': '4.151', 'learning_rate': '2.661e-05', 'epoch': '0.6061'}
{'loss': '0.5823', 'grad_norm': '6.704', 'learning_rate': '2.613e-05', 'epoch': '0.6494'}
{'loss': '0.5048', 'grad_norm': '3.8', 'learning_rate': '2.565e-05', 'epoch': '0.6926'}
{'loss': '0.4811', 'grad_norm': '5.607', 'learning_rate': '2.517e-05', 'epoch': '0.7359'}
{'loss': '0.628', 'grad_norm': '12', 'learning_rate': '2.469e-05', 'epoch': '0.7792'}
{'loss': '0.5216', 'grad_norm': '14.87', 'learning_rate': '2.421e-05', 'epoch': '0.8225'}
{'loss': '0.4703', 'grad_norm': '9.387', 'learning_rate': '2.373e-05', 'epoch': '0.8658'}
{'loss': '0.4581', 'grad_norm': '15.07', 'learning_rate': '2.324e-05', 'epoch': '0.9091'}
{'loss': '0.5326', 'grad_norm': '17.7', 'learning_rate': '2.276e-05', 'epoch': '0.9524'}
{'loss': '0.594', 'grad_norm': '5.212', 'learning_rate': '2.228e-05', 'epoch': '0.9957'}
{'eval_loss': '0.4547', 'eval_accuracy': '0.8385', 'eval_f1': '0.4524', 'eval_recall': '0.7333', 'eval_precision': '0.3271', 'eval_roc_auc': '0.7912', 'eval_runtime': '13.33', 'eval_samples_per_second': '198', 'eval_steps_per_second': '6.229', 'epoch': '1'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.3918', 'grad_norm': '62.34', 'learning_rate': '2.18e-05', 'epoch': '1.039'}
{'loss': '0.5383', 'grad_norm': '1.27', 'learning_rate': '2.132e-05', 'epoch': '1.082'}
{'loss': '0.3919', 'grad_norm': '5.915', 'learning_rate': '2.084e-05', 'epoch': '1.126'}
{'loss': '0.3691', 'grad_norm': '1.752', 'learning_rate': '2.036e-05', 'epoch': '1.169'}
{'loss': '0.5005', 'grad_norm': '7.198', 'learning_rate': '1.988e-05', 'epoch': '1.212'}
{'loss': '0.4117', 'grad_norm': '8.125', 'learning_rate': '1.94e-05', 'epoch': '1.255'}
{'loss': '0.4824', 'grad_norm': '35.61', 'learning_rate': '1.892e-05', 'epoch': '1.299'}
{'loss': '0.4245', 'grad_norm': '3.532', 'learning_rate': '1.843e-05', 'epoch': '1.342'}
{'loss': '0.4363', 'grad_norm': '2.763', 'learning_rate': '1.795e-05', 'epoch': '1.385'}
{'loss': '0.3902', 'grad_norm': '5.495', 'learning_rate': '1.747e-05', 'epoch': '1.429'}
{'loss': '0.5323', 'grad_norm': '23.47', 'learning_rate': '1.699e-05', 'epoch': '1.472'}
{'loss': '0.4257', 'grad_norm': '15.96', 'learning_rate': '1.651e-05', 'epoch': '1.515'}
{'loss': '0.4177', 'grad_norm': '2.885', 'learning_rate': '1.603e-05', 'epoch': '1.558'}
{'loss': '0.3634', 'grad_norm': '11.9', 'learning_rate': '1.555e-05', 'epoch': '1.602'}
{'loss': '0.4702', 'grad_norm': '0.7565', 'learning_rate': '1.507e-05', 'epoch': '1.645'}
{'loss': '0.4484', 'grad_norm': '2.555', 'learning_rate': '1.459e-05', 'epoch': '1.688'}
{'loss': '0.4057', 'grad_norm': '1.518', 'learning_rate': '1.41e-05', 'epoch': '1.732'}
{'loss': '0.4667', 'grad_norm': '13.77', 'learning_rate': '1.362e-05', 'epoch': '1.775'}
{'loss': '0.5151', 'grad_norm': '5.541', 'learning_rate': '1.314e-05', 'epoch': '1.818'}
{'loss': '0.4228', 'grad_norm': '6.484', 'learning_rate': '1.266e-05', 'epoch': '1.861'}
{'loss': '0.4449', 'grad_norm': '1.453', 'learning_rate': '1.218e-05', 'epoch': '1.905'}
{'loss': '0.352', 'grad_norm': '7.946', 'learning_rate': '1.17e-05', 'epoch': '1.948'}
{'loss': '0.4982', 'grad_norm': '5.976', 'learning_rate': '1.122e-05', 'epoch': '1.991'}
{'eval_loss': '0.7456', 'eval_accuracy': '0.9067', 'eval_f1': '0.5269', 'eval_recall': '0.5708', 'eval_precision': '0.4893', 'eval_roc_auc': '0.7556', 'eval_runtime': '13.33', 'eval_samples_per_second': '197.9', 'eval_steps_per_second': '6.225', 'epoch': '2'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.1782', 'grad_norm': '15.73', 'learning_rate': '1.074e-05', 'epoch': '2.035'}
{'loss': '0.3386', 'grad_norm': '33.94', 'learning_rate': '1.026e-05', 'epoch': '2.078'}
{'loss': '0.2725', 'grad_norm': '6.356', 'learning_rate': '9.775e-06', 'epoch': '2.121'}
{'loss': '0.245', 'grad_norm': '2.457', 'learning_rate': '9.294e-06', 'epoch': '2.165'}
{'loss': '0.227', 'grad_norm': '0.5824', 'learning_rate': '8.813e-06', 'epoch': '2.208'}
{'loss': '0.293', 'grad_norm': '13.61', 'learning_rate': '8.332e-06', 'epoch': '2.251'}
{'loss': '0.3157', 'grad_norm': '0.1188', 'learning_rate': '7.851e-06', 'epoch': '2.294'}
{'loss': '0.271', 'grad_norm': '54.93', 'learning_rate': '7.37e-06', 'epoch': '2.338'}
{'loss': '0.3512', 'grad_norm': '0.4018', 'learning_rate': '6.889e-06', 'epoch': '2.381'}
{'loss': '0.2835', 'grad_norm': '0.4049', 'learning_rate': '6.408e-06', 'epoch': '2.424'}
{'loss': '0.2787', 'grad_norm': '2.081', 'learning_rate': '5.927e-06', 'epoch': '2.468'}
{'loss': '0.3351', 'grad_norm': '7.433', 'learning_rate': '5.446e-06', 'epoch': '2.511'}
{'loss': '0.2978', 'grad_norm': '15.64', 'learning_rate': '4.965e-06', 'epoch': '2.554'}
{'loss': '0.2928', 'grad_norm': '0.5262', 'learning_rate': '4.483e-06', 'epoch': '2.597'}
{'loss': '0.1686', 'grad_norm': '31.37', 'learning_rate': '4.002e-06', 'epoch': '2.641'}
{'loss': '0.2902', 'grad_norm': '2.876', 'learning_rate': '3.521e-06', 'epoch': '2.684'}
{'loss': '0.3122', 'grad_norm': '7.376', 'learning_rate': '3.04e-06', 'epoch': '2.727'}
{'loss': '0.2705', 'grad_norm': '0.3952', 'learning_rate': '2.559e-06', 'epoch': '2.771'}
{'loss': '0.3769', 'grad_norm': '28.52', 'learning_rate': '2.078e-06', 'epoch': '2.814'}
{'loss': '0.2579', 'grad_norm': '16.23', 'learning_rate': '1.597e-06', 'epoch': '2.857'}
{'loss': '0.3796', 'grad_norm': '5.245', 'learning_rate': '1.116e-06', 'epoch': '2.9'}
{'loss': '0.2947', 'grad_norm': '19.42', 'learning_rate': '6.35e-07', 'epoch': '2.944'}
{'loss': '0.3355', 'grad_norm': '73.31', 'learning_rate': '1.539e-07', 'epoch': '2.987'}
{'eval_loss': '1.116', 'eval_accuracy': '0.9075', 'eval_f1': '0.5061', 'eval_recall': '0.5208', 'eval_precision': '0.4921', 'eval_roc_auc': '0.7335', 'eval_runtime': '13.35', 'eval_samples_per_second': '197.6', 'eval_steps_per_second': '6.217', 'epoch': '3'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'train_runtime': '1042', 'train_samples_per_second': '53.16', 'train_steps_per_second': '3.325', 'train_loss': '0.4324', 'epoch': '3'}

[I 2026-09-22 10:13:19,299] Trial 4 finished with value: 0.5269230769230769 and parameters: {'learning_rate': 3.33374837226629e-05, 'num_train_epochs': 3, 'per_device_train_batch_size': 8, 'weight_decay': 0.004947668289613083}. Best is trial 4 with value: 0.5269230769230769.

{'eval_loss': '0.7494', 'eval_accuracy': '0.9067', 'eval_f1': '0.5269', 'eval_recall': '0.5708', 'eval_precision': '0.4893', 'eval_roc_auc': '0.7556', 'eval_runtime': '13.34', 'eval_samples_per_second': '197.7', 'eval_steps_per_second': '6.221', 'epoch': '3'}

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

{'loss': '0.6288', 'grad_norm': '2.419', 'learning_rate': '2.453e-05', 'epoch': '0.08651'}
{'loss': '0.4735', 'grad_norm': '13.69', 'learning_rate': '2.38e-05', 'epoch': '0.173'}
{'loss': '0.5062', 'grad_norm': '6.191', 'learning_rate': '2.307e-05', 'epoch': '0.2595'}
{'loss': '0.552', 'grad_norm': '8.897', 'learning_rate': '2.234e-05', 'epoch': '0.346'}
{'loss': '0.4476', 'grad_norm': '10.49', 'learning_rate': '2.162e-05', 'epoch': '0.4325'}
{'loss': '0.4913', 'grad_norm': '4.453', 'learning_rate': '2.089e-05', 'epoch': '0.519'}
{'loss': '0.4769', 'grad_norm': '6.88', 'learning_rate': '2.016e-05', 'epoch': '0.6055'}
{'loss': '0.4514', 'grad_norm': '8.683', 'learning_rate': '1.943e-05', 'epoch': '0.692'}
{'loss': '0.4736', 'grad_norm': '15.78', 'learning_rate': '1.87e-05', 'epoch': '0.7785'}
{'loss': '0.4489', 'grad_norm': '4.204', 'learning_rate': '1.798e-05', 'epoch': '0.8651'}
{'loss': '0.4328', 'grad_norm': '20.37', 'learning_rate': '1.725e-05', 'epoch': '0.9516'}
{'eval_loss': '0.4583', 'eval_accuracy': '0.8404', 'eval_f1': '0.454', 'eval_recall': '0.7292', 'eval_precision': '0.3296', 'eval_roc_auc': '0.7904', 'eval_runtime': '13.32', 'eval_samples_per_second': '198.1', 'eval_steps_per_second': '6.232', 'epoch': '1'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.4203', 'grad_norm': '6.303', 'learning_rate': '1.652e-05', 'epoch': '1.038'}
{'loss': '0.3441', 'grad_norm': '6.179', 'learning_rate': '1.579e-05', 'epoch': '1.125'}
{'loss': '0.3551', 'grad_norm': '16.56', 'learning_rate': '1.507e-05', 'epoch': '1.211'}
{'loss': '0.3796', 'grad_norm': '34.04', 'learning_rate': '1.434e-05', 'epoch': '1.298'}
{'loss': '0.3821', 'grad_norm': '5.85', 'learning_rate': '1.361e-05', 'epoch': '1.384'}
{'loss': '0.321', 'grad_norm': '10.51', 'learning_rate': '1.288e-05', 'epoch': '1.471'}
{'loss': '0.3528', 'grad_norm': '24.91', 'learning_rate': '1.215e-05', 'epoch': '1.557'}
{'loss': '0.351', 'grad_norm': '5.681', 'learning_rate': '1.143e-05', 'epoch': '1.644'}
{'loss': '0.3543', 'grad_norm': '13.95', 'learning_rate': '1.07e-05', 'epoch': '1.73'}
{'loss': '0.4352', 'grad_norm': '22.95', 'learning_rate': '9.971e-06', 'epoch': '1.817'}
{'loss': '0.3446', 'grad_norm': '22.46', 'learning_rate': '9.243e-06', 'epoch': '1.903'}
{'loss': '0.3326', 'grad_norm': '17.74', 'learning_rate': '8.515e-06', 'epoch': '1.99'}
{'eval_loss': '0.4699', 'eval_accuracy': '0.8525', 'eval_f1': '0.4793', 'eval_recall': '0.7458', 'eval_precision': '0.3531', 'eval_roc_auc': '0.8045', 'eval_runtime': '13.33', 'eval_samples_per_second': '197.9', 'eval_steps_per_second': '6.226', 'epoch': '2'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.293', 'grad_norm': '3.607', 'learning_rate': '7.788e-06', 'epoch': '2.076'}
{'loss': '0.2436', 'grad_norm': '4.464', 'learning_rate': '7.06e-06', 'epoch': '2.163'}
{'loss': '0.2436', 'grad_norm': '3.853', 'learning_rate': '6.332e-06', 'epoch': '2.249'}
{'loss': '0.2116', 'grad_norm': '7.383', 'learning_rate': '5.604e-06', 'epoch': '2.336'}
{'loss': '0.292', 'grad_norm': '36.06', 'learning_rate': '4.876e-06', 'epoch': '2.422'}
{'loss': '0.2529', 'grad_norm': '2.24', 'learning_rate': '4.149e-06', 'epoch': '2.509'}
{'loss': '0.2737', 'grad_norm': '14.37', 'learning_rate': '3.421e-06', 'epoch': '2.595'}
{'loss': '0.2107', 'grad_norm': '21.86', 'learning_rate': '2.693e-06', 'epoch': '2.682'}
{'loss': '0.2755', 'grad_norm': '78.66', 'learning_rate': '1.965e-06', 'epoch': '2.768'}
{'loss': '0.2321', 'grad_norm': '4.822', 'learning_rate': '1.237e-06', 'epoch': '2.855'}
{'loss': '0.2499', 'grad_norm': '3.303', 'learning_rate': '5.095e-07', 'epoch': '2.941'}
{'eval_loss': '0.6723', 'eval_accuracy': '0.884', 'eval_f1': '0.4917', 'eval_recall': '0.6167', 'eval_precision': '0.4088', 'eval_roc_auc': '0.7637', 'eval_runtime': '13.38', 'eval_samples_per_second': '197.2', 'eval_steps_per_second': '6.204', 'epoch': '3'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'train_runtime': '829.7', 'train_samples_per_second': '66.77', 'train_steps_per_second': '2.09', 'train_loss': '0.3671', 'epoch': '3'}

[I 2026-09-22 10:27:26,077] Trial 5 finished with value: 0.49169435215946844 and parameters: {'learning_rate': 2.524036663924221e-05, 'num_train_epochs': 3, 'per_device_train_batch_size': 16, 'weight_decay': 0.07543581372573151}. Best is trial 4 with value: 0.5269230769230769.

{'eval_loss': '0.6723', 'eval_accuracy': '0.884', 'eval_f1': '0.4917', 'eval_recall': '0.6167', 'eval_precision': '0.4088', 'eval_roc_auc': '0.7637', 'eval_runtime': '13.35', 'eval_samples_per_second': '197.6', 'eval_steps_per_second': '6.216', 'epoch': '3'}

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

{'loss': '0.6612', 'grad_norm': '3.985', 'learning_rate': '1.235e-05', 'epoch': '0.08651'}
{'loss': '0.5337', 'grad_norm': '11.48', 'learning_rate': '1.217e-05', 'epoch': '0.173'}
{'loss': '0.4959', 'grad_norm': '8.129', 'learning_rate': '1.199e-05', 'epoch': '0.2595'}
{'loss': '0.5253', 'grad_norm': '7.11', 'learning_rate': '1.181e-05', 'epoch': '0.346'}
{'loss': '0.4345', 'grad_norm': '10.72', 'learning_rate': '1.163e-05', 'epoch': '0.4325'}
{'loss': '0.4918', 'grad_norm': '4.378', 'learning_rate': '1.145e-05', 'epoch': '0.519'}
{'loss': '0.4681', 'grad_norm': '9.145', 'learning_rate': '1.127e-05', 'epoch': '0.6055'}
{'loss': '0.453', 'grad_norm': '8.463', 'learning_rate': '1.108e-05', 'epoch': '0.692'}
{'loss': '0.4749', 'grad_norm': '18.89', 'learning_rate': '1.09e-05', 'epoch': '0.7785'}
{'loss': '0.4607', 'grad_norm': '4.884', 'learning_rate': '1.072e-05', 'epoch': '0.8651'}
{'loss': '0.4349', 'grad_norm': '22.67', 'learning_rate': '1.054e-05', 'epoch': '0.9516'}
{'eval_loss': '0.4514', 'eval_accuracy': '0.8222', 'eval_f1': '0.4343', 'eval_recall': '0.75', 'eval_precision': '0.3056', 'eval_roc_auc': '0.7897', 'eval_runtime': '13.33', 'eval_samples_per_second': '197.9', 'eval_steps_per_second': '6.227', 'epoch': '1'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.4252', 'grad_norm': '8.204', 'learning_rate': '1.036e-05', 'epoch': '1.038'}
{'loss': '0.3767', 'grad_norm': '8.674', 'learning_rate': '1.018e-05', 'epoch': '1.125'}
{'loss': '0.3943', 'grad_norm': '12.3', 'learning_rate': '1e-05', 'epoch': '1.211'}
{'loss': '0.3951', 'grad_norm': '35.11', 'learning_rate': '9.82e-06', 'epoch': '1.298'}
{'loss': '0.4146', 'grad_norm': '5.727', 'learning_rate': '9.64e-06', 'epoch': '1.384'}
{'loss': '0.3561', 'grad_norm': '9.89', 'learning_rate': '9.459e-06', 'epoch': '1.471'}
{'loss': '0.3854', 'grad_norm': '29.87', 'learning_rate': '9.279e-06', 'epoch': '1.557'}
{'loss': '0.3778', 'grad_norm': '5.611', 'learning_rate': '9.098e-06', 'epoch': '1.644'}
{'loss': '0.4084', 'grad_norm': '24.54', 'learning_rate': '8.917e-06', 'epoch': '1.73'}
{'loss': '0.4565', 'grad_norm': '16.9', 'learning_rate': '8.737e-06', 'epoch': '1.817'}
{'loss': '0.3952', 'grad_norm': '23.13', 'learning_rate': '8.556e-06', 'epoch': '1.903'}
{'loss': '0.3608', 'grad_norm': '10.62', 'learning_rate': '8.376e-06', 'epoch': '1.99'}
{'eval_loss': '0.4294', 'eval_accuracy': '0.8082', 'eval_f1': '0.4327', 'eval_recall': '0.8042', 'eval_precision': '0.296', 'eval_roc_auc': '0.8064', 'eval_runtime': '13.36', 'eval_samples_per_second': '197.4', 'eval_steps_per_second': '6.211', 'epoch': '2'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.3311', 'grad_norm': '7.261', 'learning_rate': '8.195e-06', 'epoch': '2.076'}
{'loss': '0.296', 'grad_norm': '6.507', 'learning_rate': '8.014e-06', 'epoch': '2.163'}
{'loss': '0.2949', 'grad_norm': '3.15', 'learning_rate': '7.834e-06', 'epoch': '2.249'}
{'loss': '0.3039', 'grad_norm': '9.315', 'learning_rate': '7.653e-06', 'epoch': '2.336'}
{'loss': '0.357', 'grad_norm': '34.94', 'learning_rate': '7.473e-06', 'epoch': '2.422'}
{'loss': '0.32', 'grad_norm': '1.912', 'learning_rate': '7.292e-06', 'epoch': '2.509'}
{'loss': '0.3345', 'grad_norm': '18.37', 'learning_rate': '7.112e-06', 'epoch': '2.595'}
{'loss': '0.2751', 'grad_norm': '18.36', 'learning_rate': '6.931e-06', 'epoch': '2.682'}
{'loss': '0.3704', 'grad_norm': '43.45', 'learning_rate': '6.75e-06', 'epoch': '2.768'}
{'loss': '0.2981', 'grad_norm': '4.763', 'learning_rate': '6.57e-06', 'epoch': '2.855'}
{'loss': '0.3057', 'grad_norm': '3.766', 'learning_rate': '6.389e-06', 'epoch': '2.941'}
{'eval_loss': '0.4898', 'eval_accuracy': '0.834', 'eval_f1': '0.4579', 'eval_recall': '0.7708', 'eval_precision': '0.3257', 'eval_roc_auc': '0.8056', 'eval_runtime': '13.34', 'eval_samples_per_second': '197.8', 'eval_steps_per_second': '6.224', 'epoch': '3'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.2841', 'grad_norm': '88.68', 'learning_rate': '6.209e-06', 'epoch': '3.028'}
{'loss': '0.2663', 'grad_norm': '19.19', 'learning_rate': '6.028e-06', 'epoch': '3.114'}
{'loss': '0.2536', 'grad_norm': '10.16', 'learning_rate': '5.847e-06', 'epoch': '3.201'}
{'loss': '0.2525', 'grad_norm': '7.138', 'learning_rate': '5.667e-06', 'epoch': '3.287'}
{'loss': '0.2464', 'grad_norm': '10.78', 'learning_rate': '5.486e-06', 'epoch': '3.374'}
{'loss': '0.2719', 'grad_norm': '9.621', 'learning_rate': '5.306e-06', 'epoch': '3.46'}
{'loss': '0.2754', 'grad_norm': '5.846', 'learning_rate': '5.125e-06', 'epoch': '3.547'}
{'loss': '0.3241', 'grad_norm': '35.92', 'learning_rate': '4.944e-06', 'epoch': '3.633'}
{'loss': '0.2561', 'grad_norm': '24.68', 'learning_rate': '4.764e-06', 'epoch': '3.72'}
{'loss': '0.2447', 'grad_norm': '31.59', 'learning_rate': '4.583e-06', 'epoch': '3.806'}
{'loss': '0.2339', 'grad_norm': '5.57', 'learning_rate': '4.403e-06', 'epoch': '3.893'}
{'loss': '0.2671', 'grad_norm': '6.235', 'learning_rate': '4.222e-06', 'epoch': '3.979'}
{'eval_loss': '0.7348', 'eval_accuracy': '0.8931', 'eval_f1': '0.4964', 'eval_recall': '0.5792', 'eval_precision': '0.4344', 'eval_roc_auc': '0.7518', 'eval_runtime': '13.41', 'eval_samples_per_second': '196.8', 'eval_steps_per_second': '6.191', 'epoch': '4'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.1712', 'grad_norm': '3.281', 'learning_rate': '4.042e-06', 'epoch': '4.066'}
{'loss': '0.2135', 'grad_norm': '12.17', 'learning_rate': '3.861e-06', 'epoch': '4.152'}
{'loss': '0.2158', 'grad_norm': '31.56', 'learning_rate': '3.68e-06', 'epoch': '4.239'}
{'loss': '0.1978', 'grad_norm': '44.91', 'learning_rate': '3.5e-06', 'epoch': '4.325'}
{'loss': '0.1809', 'grad_norm': '17.88', 'learning_rate': '3.319e-06', 'epoch': '4.412'}
{'loss': '0.185', 'grad_norm': '25.29', 'learning_rate': '3.139e-06', 'epoch': '4.498'}
{'loss': '0.253', 'grad_norm': '3.302', 'learning_rate': '2.958e-06', 'epoch': '4.585'}
{'loss': '0.1793', 'grad_norm': '5.163', 'learning_rate': '2.777e-06', 'epoch': '4.671'}
{'loss': '0.2339', 'grad_norm': '1.716', 'learning_rate': '2.597e-06', 'epoch': '4.758'}
{'loss': '0.229', 'grad_norm': '17.01', 'learning_rate': '2.416e-06', 'epoch': '4.844'}
{'loss': '0.1743', 'grad_norm': '3.894', 'learning_rate': '2.236e-06', 'epoch': '4.931'}
{'eval_loss': '0.9448', 'eval_accuracy': '0.9007', 'eval_f1': '0.476', 'eval_recall': '0.4958', 'eval_precision': '0.4577', 'eval_roc_auc': '0.7185', 'eval_runtime': '13.44', 'eval_samples_per_second': '196.3', 'eval_steps_per_second': '6.176', 'epoch': '5'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.1941', 'grad_norm': '11.65', 'learning_rate': '2.055e-06', 'epoch': '5.017'}
{'loss': '0.193', 'grad_norm': '2.53', 'learning_rate': '1.874e-06', 'epoch': '5.104'}
{'loss': '0.162', 'grad_norm': '28.73', 'learning_rate': '1.694e-06', 'epoch': '5.19'}
{'loss': '0.1844', 'grad_norm': '1.341', 'learning_rate': '1.513e-06', 'epoch': '5.277'}
{'loss': '0.1326', 'grad_norm': '23.78', 'learning_rate': '1.333e-06', 'epoch': '5.363'}
{'loss': '0.1252', 'grad_norm': '3.33', 'learning_rate': '1.152e-06', 'epoch': '5.45'}
{'loss': '0.1421', 'grad_norm': '10.66', 'learning_rate': '9.716e-07', 'epoch': '5.536'}
{'loss': '0.1438', 'grad_norm': '0.7678', 'learning_rate': '7.91e-07', 'epoch': '5.623'}
{'loss': '0.228', 'grad_norm': '2.4', 'learning_rate': '6.104e-07', 'epoch': '5.709'}
{'loss': '0.166', 'grad_norm': '0.7521', 'learning_rate': '4.298e-07', 'epoch': '5.796'}
{'loss': '0.1742', 'grad_norm': '3.056', 'learning_rate': '2.492e-07', 'epoch': '5.882'}
{'loss': '0.1244', 'grad_norm': '81.77', 'learning_rate': '6.862e-08', 'epoch': '5.969'}
{'eval_loss': '0.933', 'eval_accuracy': '0.895', 'eval_f1': '0.4861', 'eval_recall': '0.5458', 'eval_precision': '0.4381', 'eval_roc_auc': '0.7379', 'eval_runtime': '13.61', 'eval_samples_per_second': '193.8', 'eval_steps_per_second': '6.097', 'epoch': '6'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'train_runtime': '1660', 'train_samples_per_second': '66.76', 'train_steps_per_second': '2.09', 'train_loss': '0.3044', 'epoch': '6'}

[I 2026-09-22 10:55:22,546] Trial 6 finished with value: 0.4982078853046595 and parameters: {'learning_rate': 1.2525557463475891e-05, 'num_train_epochs': 6, 'per_device_train_batch_size': 16, 'weight_decay': 0.02159897576832879}. Best is trial 4 with value: 0.5269230769230769.

{'eval_loss': '0.737', 'eval_accuracy': '0.8939', 'eval_f1': '0.4982', 'eval_recall': '0.5792', 'eval_precision': '0.4371', 'eval_roc_auc': '0.7523', 'eval_runtime': '13.41', 'eval_samples_per_second': '196.7', 'eval_steps_per_second': '6.188', 'epoch': '6'}

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

{'loss': '0.6482', 'grad_norm': '2.51', 'learning_rate': '1.721e-05', 'epoch': '0.08651'}
{'loss': '0.4998', 'grad_norm': '12.45', 'learning_rate': '1.683e-05', 'epoch': '0.173'}
{'loss': '0.4992', 'grad_norm': '7.6', 'learning_rate': '1.645e-05', 'epoch': '0.2595'}
{'loss': '0.5411', 'grad_norm': '7.004', 'learning_rate': '1.607e-05', 'epoch': '0.346'}
{'loss': '0.4373', 'grad_norm': '10.64', 'learning_rate': '1.569e-05', 'epoch': '0.4325'}
{'loss': '0.4954', 'grad_norm': '4.239', 'learning_rate': '1.531e-05', 'epoch': '0.519'}
{'loss': '0.4715', 'grad_norm': '8.105', 'learning_rate': '1.493e-05', 'epoch': '0.6055'}
{'loss': '0.4536', 'grad_norm': '8.353', 'learning_rate': '1.455e-05', 'epoch': '0.692'}
{'loss': '0.4708', 'grad_norm': '16.16', 'learning_rate': '1.417e-05', 'epoch': '0.7785'}
{'loss': '0.4535', 'grad_norm': '4.759', 'learning_rate': '1.379e-05', 'epoch': '0.8651'}
{'loss': '0.434', 'grad_norm': '22.4', 'learning_rate': '1.341e-05', 'epoch': '0.9516'}
{'eval_loss': '0.4498', 'eval_accuracy': '0.8249', 'eval_f1': '0.4393', 'eval_recall': '0.7542', 'eval_precision': '0.3099', 'eval_roc_auc': '0.7931', 'eval_runtime': '13.43', 'eval_samples_per_second': '196.4', 'eval_steps_per_second': '6.181', 'epoch': '1'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.4137', 'grad_norm': '7.34', 'learning_rate': '1.303e-05', 'epoch': '1.038'}
{'loss': '0.3604', 'grad_norm': '7.562', 'learning_rate': '1.265e-05', 'epoch': '1.125'}
{'loss': '0.3707', 'grad_norm': '13.29', 'learning_rate': '1.226e-05', 'epoch': '1.211'}
{'loss': '0.3887', 'grad_norm': '42.2', 'learning_rate': '1.188e-05', 'epoch': '1.298'}
{'loss': '0.3935', 'grad_norm': '5.638', 'learning_rate': '1.15e-05', 'epoch': '1.384'}
{'loss': '0.3429', 'grad_norm': '10.38', 'learning_rate': '1.112e-05', 'epoch': '1.471'}
{'loss': '0.3671', 'grad_norm': '27.44', 'learning_rate': '1.074e-05', 'epoch': '1.557'}
{'loss': '0.3666', 'grad_norm': '5.311', 'learning_rate': '1.036e-05', 'epoch': '1.644'}
{'loss': '0.3847', 'grad_norm': '14.55', 'learning_rate': '9.984e-06', 'epoch': '1.73'}
{'loss': '0.4416', 'grad_norm': '18.2', 'learning_rate': '9.604e-06', 'epoch': '1.817'}
{'loss': '0.3712', 'grad_norm': '24.58', 'learning_rate': '9.223e-06', 'epoch': '1.903'}
{'loss': '0.3431', 'grad_norm': '11.96', 'learning_rate': '8.843e-06', 'epoch': '1.99'}
{'eval_loss': '0.4383', 'eval_accuracy': '0.8154', 'eval_f1': '0.4434', 'eval_recall': '0.8083', 'eval_precision': '0.3055', 'eval_roc_auc': '0.8122', 'eval_runtime': '13.4', 'eval_samples_per_second': '196.9', 'eval_steps_per_second': '6.195', 'epoch': '2'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.3134', 'grad_norm': '6.069', 'learning_rate': '8.463e-06', 'epoch': '2.076'}
{'loss': '0.2769', 'grad_norm': '6.073', 'learning_rate': '8.083e-06', 'epoch': '2.163'}
{'loss': '0.2599', 'grad_norm': '3.168', 'learning_rate': '7.703e-06', 'epoch': '2.249'}
{'loss': '0.2505', 'grad_norm': '8.657', 'learning_rate': '7.322e-06', 'epoch': '2.336'}
{'loss': '0.3269', 'grad_norm': '31.54', 'learning_rate': '6.942e-06', 'epoch': '2.422'}
{'loss': '0.2816', 'grad_norm': '1.925', 'learning_rate': '6.562e-06', 'epoch': '2.509'}
{'loss': '0.3018', 'grad_norm': '21.52', 'learning_rate': '6.182e-06', 'epoch': '2.595'}
{'loss': '0.2449', 'grad_norm': '18.19', 'learning_rate': '5.802e-06', 'epoch': '2.682'}
{'loss': '0.3158', 'grad_norm': '57.22', 'learning_rate': '5.422e-06', 'epoch': '2.768'}
{'loss': '0.2786', 'grad_norm': '3.29', 'learning_rate': '5.041e-06', 'epoch': '2.855'}
{'loss': '0.2793', 'grad_norm': '3.467', 'learning_rate': '4.661e-06', 'epoch': '2.941'}
{'eval_loss': '0.5484', 'eval_accuracy': '0.8613', 'eval_f1': '0.4831', 'eval_recall': '0.7125', 'eval_precision': '0.3654', 'eval_roc_auc': '0.7943', 'eval_runtime': '13.42', 'eval_samples_per_second': '196.6', 'eval_steps_per_second': '6.187', 'epoch': '3'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.261', 'grad_norm': '4.937', 'learning_rate': '4.281e-06', 'epoch': '3.028'}
{'loss': '0.214', 'grad_norm': '21.82', 'learning_rate': '3.901e-06', 'epoch': '3.114'}
{'loss': '0.2169', 'grad_norm': '6.878', 'learning_rate': '3.521e-06', 'epoch': '3.201'}
{'loss': '0.2331', 'grad_norm': '5.193', 'learning_rate': '3.14e-06', 'epoch': '3.287'}
{'loss': '0.2057', 'grad_norm': '6.84', 'learning_rate': '2.76e-06', 'epoch': '3.374'}
{'loss': '0.2339', 'grad_norm': '23.65', 'learning_rate': '2.38e-06', 'epoch': '3.46'}
{'loss': '0.2324', 'grad_norm': '5.265', 'learning_rate': '2e-06', 'epoch': '3.547'}
{'loss': '0.2972', 'grad_norm': '11.09', 'learning_rate': '1.62e-06', 'epoch': '3.633'}
{'loss': '0.2103', 'grad_norm': '15.93', 'learning_rate': '1.239e-06', 'epoch': '3.72'}
{'loss': '0.2007', 'grad_norm': '35.32', 'learning_rate': '8.592e-07', 'epoch': '3.806'}
{'loss': '0.208', 'grad_norm': '4.409', 'learning_rate': '4.79e-07', 'epoch': '3.893'}
{'loss': '0.2461', 'grad_norm': '5.379', 'learning_rate': '9.885e-08', 'epoch': '3.979'}
{'eval_loss': '0.7116', 'eval_accuracy': '0.8855', 'eval_f1': '0.5017', 'eval_recall': '0.6333', 'eval_precision': '0.4153', 'eval_roc_auc': '0.772', 'eval_runtime': '13.4', 'eval_samples_per_second': '196.8', 'eval_steps_per_second': '6.193', 'epoch': '4'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'train_runtime': '1109', 'train_samples_per_second': '66.63', 'train_steps_per_second': '2.086', 'train_loss': '0.3433', 'epoch': '4'}

[I 2026-09-22 11:14:08,340] Trial 7 finished with value: 0.5016501650165016 and parameters: {'learning_rate': 1.7579962320757415e-05, 'num_train_epochs': 4, 'per_device_train_batch_size': 16, 'weight_decay': 0.047837532326511625}. Best is trial 4 with value: 0.5269230769230769.

{'eval_loss': '0.7116', 'eval_accuracy': '0.8855', 'eval_f1': '0.5017', 'eval_recall': '0.6333', 'eval_precision': '0.4153', 'eval_roc_auc': '0.772', 'eval_runtime': '13.56', 'eval_samples_per_second': '194.5', 'eval_steps_per_second': '6.119', 'epoch': '4'}

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

{'loss': '0.6608', 'grad_norm': '4.91', 'learning_rate': '1.225e-05', 'epoch': '0.08651'}
{'loss': '0.5345', 'grad_norm': '11.33', 'learning_rate': '1.207e-05', 'epoch': '0.173'}
{'loss': '0.4926', 'grad_norm': '7.957', 'learning_rate': '1.189e-05', 'epoch': '0.2595'}
{'loss': '0.5255', 'grad_norm': '7.724', 'learning_rate': '1.171e-05', 'epoch': '0.346'}
{'loss': '0.4302', 'grad_norm': '11.01', 'learning_rate': '1.153e-05', 'epoch': '0.4325'}
{'loss': '0.4943', 'grad_norm': '4.336', 'learning_rate': '1.135e-05', 'epoch': '0.519'}
{'loss': '0.4698', 'grad_norm': '10.16', 'learning_rate': '1.117e-05', 'epoch': '0.6055'}
{'loss': '0.4568', 'grad_norm': '8.052', 'learning_rate': '1.1e-05', 'epoch': '0.692'}
{'loss': '0.4741', 'grad_norm': '17.99', 'learning_rate': '1.082e-05', 'epoch': '0.7785'}
{'loss': '0.4556', 'grad_norm': '4.893', 'learning_rate': '1.064e-05', 'epoch': '0.8651'}
{'loss': '0.4338', 'grad_norm': '22.73', 'learning_rate': '1.046e-05', 'epoch': '0.9516'}
{'eval_loss': '0.4532', 'eval_accuracy': '0.823', 'eval_f1': '0.4339', 'eval_recall': '0.7458', 'eval_precision': '0.306', 'eval_roc_auc': '0.7883', 'eval_runtime': '13.41', 'eval_samples_per_second': '196.8', 'eval_steps_per_second': '6.192', 'epoch': '1'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.4259', 'grad_norm': '8.342', 'learning_rate': '1.028e-05', 'epoch': '1.038'}
{'loss': '0.371', 'grad_norm': '8.557', 'learning_rate': '1.01e-05', 'epoch': '1.125'}
{'loss': '0.3984', 'grad_norm': '13.23', 'learning_rate': '9.92e-06', 'epoch': '1.211'}
{'loss': '0.3869', 'grad_norm': '39.75', 'learning_rate': '9.741e-06', 'epoch': '1.298'}
{'loss': '0.4205', 'grad_norm': '6.318', 'learning_rate': '9.562e-06', 'epoch': '1.384'}
{'loss': '0.3567', 'grad_norm': '10.14', 'learning_rate': '9.383e-06', 'epoch': '1.471'}
{'loss': '0.3802', 'grad_norm': '30.83', 'learning_rate': '9.204e-06', 'epoch': '1.557'}
{'loss': '0.3795', 'grad_norm': '6.012', 'learning_rate': '9.025e-06', 'epoch': '1.644'}
{'loss': '0.3982', 'grad_norm': '16.28', 'learning_rate': '8.845e-06', 'epoch': '1.73'}
{'loss': '0.4554', 'grad_norm': '16.62', 'learning_rate': '8.666e-06', 'epoch': '1.817'}
{'loss': '0.4008', 'grad_norm': '26.52', 'learning_rate': '8.487e-06', 'epoch': '1.903'}
{'loss': '0.3641', 'grad_norm': '13.27', 'learning_rate': '8.308e-06', 'epoch': '1.99'}
{'eval_loss': '0.4333', 'eval_accuracy': '0.8059', 'eval_f1': '0.4286', 'eval_recall': '0.8', 'eval_precision': '0.2927', 'eval_roc_auc': '0.8033', 'eval_runtime': '13.4', 'eval_samples_per_second': '196.8', 'eval_steps_per_second': '6.192', 'epoch': '2'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.3263', 'grad_norm': '8.186', 'learning_rate': '8.129e-06', 'epoch': '2.076'}
{'loss': '0.2958', 'grad_norm': '8.001', 'learning_rate': '7.95e-06', 'epoch': '2.163'}
{'loss': '0.2952', 'grad_norm': '2.886', 'learning_rate': '7.771e-06', 'epoch': '2.249'}
{'loss': '0.2958', 'grad_norm': '9.025', 'learning_rate': '7.592e-06', 'epoch': '2.336'}
{'loss': '0.357', 'grad_norm': '34.42', 'learning_rate': '7.412e-06', 'epoch': '2.422'}
{'loss': '0.3163', 'grad_norm': '2.16', 'learning_rate': '7.233e-06', 'epoch': '2.509'}
{'loss': '0.3329', 'grad_norm': '19.03', 'learning_rate': '7.054e-06', 'epoch': '2.595'}
{'loss': '0.2719', 'grad_norm': '18.54', 'learning_rate': '6.875e-06', 'epoch': '2.682'}
{'loss': '0.3657', 'grad_norm': '43.72', 'learning_rate': '6.696e-06', 'epoch': '2.768'}
{'loss': '0.3023', 'grad_norm': '3.97', 'learning_rate': '6.517e-06', 'epoch': '2.855'}
{'loss': '0.3067', 'grad_norm': '3.689', 'learning_rate': '6.338e-06', 'epoch': '2.941'}
{'eval_loss': '0.4911', 'eval_accuracy': '0.8389', 'eval_f1': '0.4681', 'eval_recall': '0.7792', 'eval_precision': '0.3345', 'eval_roc_auc': '0.812', 'eval_runtime': '13.4', 'eval_samples_per_second': '196.9', 'eval_steps_per_second': '6.195', 'epoch': '3'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.2873', 'grad_norm': '20.79', 'learning_rate': '6.159e-06', 'epoch': '3.028'}
{'loss': '0.2561', 'grad_norm': '25.37', 'learning_rate': '5.979e-06', 'epoch': '3.114'}
{'loss': '0.2496', 'grad_norm': '8.68', 'learning_rate': '5.8e-06', 'epoch': '3.201'}
{'loss': '0.2482', 'grad_norm': '9.031', 'learning_rate': '5.621e-06', 'epoch': '3.287'}
{'loss': '0.2412', 'grad_norm': '8.83', 'learning_rate': '5.442e-06', 'epoch': '3.374'}
{'loss': '0.2649', 'grad_norm': '6.677', 'learning_rate': '5.263e-06', 'epoch': '3.46'}
{'loss': '0.2816', 'grad_norm': '7.011', 'learning_rate': '5.084e-06', 'epoch': '3.547'}
{'loss': '0.3221', 'grad_norm': '32.96', 'learning_rate': '4.905e-06', 'epoch': '3.633'}
{'loss': '0.2507', 'grad_norm': '21.03', 'learning_rate': '4.725e-06', 'epoch': '3.72'}
{'loss': '0.2364', 'grad_norm': '31.59', 'learning_rate': '4.546e-06', 'epoch': '3.806'}
{'loss': '0.2292', 'grad_norm': '5.414', 'learning_rate': '4.367e-06', 'epoch': '3.893'}
{'loss': '0.2682', 'grad_norm': '6.75', 'learning_rate': '4.188e-06', 'epoch': '3.979'}
{'eval_loss': '0.7306', 'eval_accuracy': '0.8927', 'eval_f1': '0.5026', 'eval_recall': '0.5958', 'eval_precision': '0.4347', 'eval_roc_auc': '0.7591', 'eval_runtime': '13.38', 'eval_samples_per_second': '197.2', 'eval_steps_per_second': '6.205', 'epoch': '4'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.1714', 'grad_norm': '3.53', 'learning_rate': '4.009e-06', 'epoch': '4.066'}
{'loss': '0.2145', 'grad_norm': '15.61', 'learning_rate': '3.83e-06', 'epoch': '4.152'}
{'loss': '0.2212', 'grad_norm': '32.24', 'learning_rate': '3.651e-06', 'epoch': '4.239'}
{'loss': '0.1902', 'grad_norm': '43.2', 'learning_rate': '3.472e-06', 'epoch': '4.325'}
{'loss': '0.1865', 'grad_norm': '29.39', 'learning_rate': '3.292e-06', 'epoch': '4.412'}
{'loss': '0.1766', 'grad_norm': '33.27', 'learning_rate': '3.113e-06', 'epoch': '4.498'}
{'loss': '0.2479', 'grad_norm': '3.157', 'learning_rate': '2.934e-06', 'epoch': '4.585'}
{'loss': '0.1816', 'grad_norm': '4.943', 'learning_rate': '2.755e-06', 'epoch': '4.671'}
{'loss': '0.2236', 'grad_norm': '0.9981', 'learning_rate': '2.576e-06', 'epoch': '4.758'}
{'loss': '0.212', 'grad_norm': '12.31', 'learning_rate': '2.397e-06', 'epoch': '4.844'}
{'loss': '0.1821', 'grad_norm': '5.482', 'learning_rate': '2.218e-06', 'epoch': '4.931'}
{'eval_loss': '0.9562', 'eval_accuracy': '0.8988', 'eval_f1': '0.4775', 'eval_recall': '0.5083', 'eval_precision': '0.4502', 'eval_roc_auc': '0.7231', 'eval_runtime': '13.42', 'eval_samples_per_second': '196.5', 'eval_steps_per_second': '6.184', 'epoch': '5'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.1817', 'grad_norm': '7.969', 'learning_rate': '2.039e-06', 'epoch': '5.017'}
{'loss': '0.1917', 'grad_norm': '8.997', 'learning_rate': '1.859e-06', 'epoch': '5.104'}
{'loss': '0.1534', 'grad_norm': '30.15', 'learning_rate': '1.68e-06', 'epoch': '5.19'}
{'loss': '0.1868', 'grad_norm': '1.513', 'learning_rate': '1.501e-06', 'epoch': '5.277'}
{'loss': '0.1252', 'grad_norm': '24.02', 'learning_rate': '1.322e-06', 'epoch': '5.363'}
{'loss': '0.1267', 'grad_norm': '3.29', 'learning_rate': '1.143e-06', 'epoch': '5.45'}
{'loss': '0.1409', 'grad_norm': '10.31', 'learning_rate': '9.637e-07', 'epoch': '5.536'}
{'loss': '0.1515', 'grad_norm': '1.013', 'learning_rate': '7.846e-07', 'epoch': '5.623'}
{'loss': '0.2337', 'grad_norm': '2.875', 'learning_rate': '6.055e-07', 'epoch': '5.709'}
{'loss': '0.1629', 'grad_norm': '1.091', 'learning_rate': '4.263e-07', 'epoch': '5.796'}
{'loss': '0.1633', 'grad_norm': '3.501', 'learning_rate': '2.472e-07', 'epoch': '5.882'}
{'loss': '0.1149', 'grad_norm': '52.16', 'learning_rate': '6.807e-08', 'epoch': '5.969'}
{'eval_loss': '0.9472', 'eval_accuracy': '0.8942', 'eval_f1': '0.4881', 'eval_recall': '0.5542', 'eval_precision': '0.4361', 'eval_roc_auc': '0.7412', 'eval_runtime': '13.41', 'eval_samples_per_second': '196.7', 'eval_steps_per_second': '6.188', 'epoch': '6'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'train_runtime': '1662', 'train_samples_per_second': '66.65', 'train_steps_per_second': '2.086', 'train_loss': '0.3023', 'epoch': '6'}

[I 2026-09-22 11:42:07,679] Trial 8 finished with value: 0.5 and parameters: {'learning_rate': 1.2424499199687197e-05, 'num_train_epochs': 6, 'per_device_train_batch_size': 16, 'weight_decay': 0.013236904489838209}. Best is trial 4 with value: 0.5269230769230769.

{'eval_loss': '0.7333', 'eval_accuracy': '0.8923', 'eval_f1': '0.5', 'eval_recall': '0.5917', 'eval_precision': '0.4329', 'eval_roc_auc': '0.7571', 'eval_runtime': '13.56', 'eval_samples_per_second': '194.6', 'eval_steps_per_second': '6.122', 'epoch': '6'}

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

{'loss': '0.6915', 'grad_norm': '11.2', 'learning_rate': '2.334e-05', 'epoch': '0.04329'}
{'loss': '0.5347', 'grad_norm': '13.98', 'learning_rate': '2.317e-05', 'epoch': '0.08658'}
{'loss': '0.5506', 'grad_norm': '4.13', 'learning_rate': '2.3e-05', 'epoch': '0.1299'}
{'loss': '0.5468', 'grad_norm': '15.43', 'learning_rate': '2.283e-05', 'epoch': '0.1732'}
{'loss': '0.5205', 'grad_norm': '12.48', 'learning_rate': '2.266e-05', 'epoch': '0.2165'}
{'loss': '0.6558', 'grad_norm': '3.951', 'learning_rate': '2.249e-05', 'epoch': '0.2597'}
{'loss': '0.6618', 'grad_norm': '10.95', 'learning_rate': '2.232e-05', 'epoch': '0.303'}
{'loss': '0.5981', 'grad_norm': '3.33', 'learning_rate': '2.215e-05', 'epoch': '0.3463'}
{'loss': '0.4697', 'grad_norm': '11.56', 'learning_rate': '2.198e-05', 'epoch': '0.3896'}
{'loss': '0.5599', 'grad_norm': '6.653', 'learning_rate': '2.182e-05', 'epoch': '0.4329'}
{'loss': '0.6247', 'grad_norm': '4.84', 'learning_rate': '2.165e-05', 'epoch': '0.4762'}
{'loss': '0.5408', 'grad_norm': '7.506', 'learning_rate': '2.148e-05', 'epoch': '0.5195'}
{'loss': '0.4989', 'grad_norm': '4.196', 'learning_rate': '2.131e-05', 'epoch': '0.5628'}
{'loss': '0.4822', 'grad_norm': '3.839', 'learning_rate': '2.114e-05', 'epoch': '0.6061'}
{'loss': '0.5504', 'grad_norm': '7.621', 'learning_rate': '2.097e-05', 'epoch': '0.6494'}
{'loss': '0.4838', 'grad_norm': '4.649', 'learning_rate': '2.08e-05', 'epoch': '0.6926'}
{'loss': '0.4508', 'grad_norm': '8.733', 'learning_rate': '2.063e-05', 'epoch': '0.7359'}
{'loss': '0.6189', 'grad_norm': '17.85', 'learning_rate': '2.046e-05', 'epoch': '0.7792'}
{'loss': '0.5176', 'grad_norm': '12.88', 'learning_rate': '2.029e-05', 'epoch': '0.8225'}
{'loss': '0.4914', 'grad_norm': '4.218', 'learning_rate': '2.012e-05', 'epoch': '0.8658'}
{'loss': '0.439', 'grad_norm': '8.478', 'learning_rate': '1.995e-05', 'epoch': '0.9091'}
{'loss': '0.5313', 'grad_norm': '16.71', 'learning_rate': '1.978e-05', 'epoch': '0.9524'}
{'loss': '0.5727', 'grad_norm': '4.481', 'learning_rate': '1.961e-05', 'epoch': '0.9957'}
{'eval_loss': '0.4473', 'eval_accuracy': '0.8434', 'eval_f1': '0.4643', 'eval_recall': '0.7458', 'eval_precision': '0.3371', 'eval_roc_auc': '0.7995', 'eval_runtime': '13.34', 'eval_samples_per_second': '197.8', 'eval_steps_per_second': '6.222', 'epoch': '1'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.398', 'grad_norm': '56.57', 'learning_rate': '1.944e-05', 'epoch': '1.039'}
{'loss': '0.4901', 'grad_norm': '2.64', 'learning_rate': '1.927e-05', 'epoch': '1.082'}
{'loss': '0.3665', 'grad_norm': '8.673', 'learning_rate': '1.91e-05', 'epoch': '1.126'}
{'loss': '0.3683', 'grad_norm': '1.655', 'learning_rate': '1.893e-05', 'epoch': '1.169'}
{'loss': '0.4692', 'grad_norm': '6.653', 'learning_rate': '1.876e-05', 'epoch': '1.212'}
{'loss': '0.4133', 'grad_norm': '8.766', 'learning_rate': '1.859e-05', 'epoch': '1.255'}
{'loss': '0.4779', 'grad_norm': '25.64', 'learning_rate': '1.842e-05', 'epoch': '1.299'}
{'loss': '0.4219', 'grad_norm': '4.174', 'learning_rate': '1.825e-05', 'epoch': '1.342'}
{'loss': '0.4647', 'grad_norm': '2.861', 'learning_rate': '1.808e-05', 'epoch': '1.385'}
{'loss': '0.3503', 'grad_norm': '1.936', 'learning_rate': '1.791e-05', 'epoch': '1.429'}
{'loss': '0.4647', 'grad_norm': '18.09', 'learning_rate': '1.774e-05', 'epoch': '1.472'}
{'loss': '0.4224', 'grad_norm': '23.12', 'learning_rate': '1.757e-05', 'epoch': '1.515'}
{'loss': '0.4307', 'grad_norm': '5.009', 'learning_rate': '1.741e-05', 'epoch': '1.558'}
{'loss': '0.3598', 'grad_norm': '9.268', 'learning_rate': '1.724e-05', 'epoch': '1.602'}
{'loss': '0.5021', 'grad_norm': '0.6957', 'learning_rate': '1.707e-05', 'epoch': '1.645'}
{'loss': '0.4631', 'grad_norm': '3.8', 'learning_rate': '1.69e-05', 'epoch': '1.688'}
{'loss': '0.4554', 'grad_norm': '0.9964', 'learning_rate': '1.673e-05', 'epoch': '1.732'}
{'loss': '0.4788', 'grad_norm': '31.71', 'learning_rate': '1.656e-05', 'epoch': '1.775'}
{'loss': '0.4839', 'grad_norm': '18.37', 'learning_rate': '1.639e-05', 'epoch': '1.818'}
{'loss': '0.4742', 'grad_norm': '10.41', 'learning_rate': '1.622e-05', 'epoch': '1.861'}
{'loss': '0.4655', 'grad_norm': '0.9348', 'learning_rate': '1.605e-05', 'epoch': '1.905'}
{'loss': '0.3912', 'grad_norm': '5.84', 'learning_rate': '1.588e-05', 'epoch': '1.948'}
{'loss': '0.5026', 'grad_norm': '4.524', 'learning_rate': '1.571e-05', 'epoch': '1.991'}
{'eval_loss': '0.7346', 'eval_accuracy': '0.9045', 'eval_f1': '0.5209', 'eval_recall': '0.5708', 'eval_precision': '0.479', 'eval_roc_auc': '0.7543', 'eval_runtime': '13.36', 'eval_samples_per_second': '197.5', 'eval_steps_per_second': '6.213', 'epoch': '2'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.2065', 'grad_norm': '14.51', 'learning_rate': '1.554e-05', 'epoch': '2.035'}
{'loss': '0.4013', 'grad_norm': '65.88', 'learning_rate': '1.537e-05', 'epoch': '2.078'}
{'loss': '0.2381', 'grad_norm': '1.431', 'learning_rate': '1.52e-05', 'epoch': '2.121'}
{'loss': '0.279', 'grad_norm': '27.9', 'learning_rate': '1.503e-05', 'epoch': '2.165'}
{'loss': '0.2761', 'grad_norm': '0.1009', 'learning_rate': '1.486e-05', 'epoch': '2.208'}
{'loss': '0.3215', 'grad_norm': '16.45', 'learning_rate': '1.469e-05', 'epoch': '2.251'}
{'loss': '0.3098', 'grad_norm': '0.1395', 'learning_rate': '1.452e-05', 'epoch': '2.294'}
{'loss': '0.3139', 'grad_norm': '31.83', 'learning_rate': '1.435e-05', 'epoch': '2.338'}
{'loss': '0.325', 'grad_norm': '0.2178', 'learning_rate': '1.418e-05', 'epoch': '2.381'}
{'loss': '0.3378', 'grad_norm': '1.936', 'learning_rate': '1.401e-05', 'epoch': '2.424'}
{'loss': '0.2826', 'grad_norm': '30.9', 'learning_rate': '1.384e-05', 'epoch': '2.468'}
{'loss': '0.3972', 'grad_norm': '7.132', 'learning_rate': '1.367e-05', 'epoch': '2.511'}
{'loss': '0.4051', 'grad_norm': '32.86', 'learning_rate': '1.35e-05', 'epoch': '2.554'}
{'loss': '0.3675', 'grad_norm': '41.09', 'learning_rate': '1.333e-05', 'epoch': '2.597'}
{'loss': '0.2464', 'grad_norm': '59.95', 'learning_rate': '1.317e-05', 'epoch': '2.641'}
{'loss': '0.3345', 'grad_norm': '3.875', 'learning_rate': '1.3e-05', 'epoch': '2.684'}
{'loss': '0.3591', 'grad_norm': '16.68', 'learning_rate': '1.283e-05', 'epoch': '2.727'}
{'loss': '0.2662', 'grad_norm': '0.7792', 'learning_rate': '1.266e-05', 'epoch': '2.771'}
{'loss': '0.3773', 'grad_norm': '34.08', 'learning_rate': '1.249e-05', 'epoch': '2.814'}
{'loss': '0.3859', 'grad_norm': '20.67', 'learning_rate': '1.232e-05', 'epoch': '2.857'}
{'loss': '0.4212', 'grad_norm': '7.633', 'learning_rate': '1.215e-05', 'epoch': '2.9'}
{'loss': '0.2482', 'grad_norm': '15.39', 'learning_rate': '1.198e-05', 'epoch': '2.944'}
{'loss': '0.3848', 'grad_norm': '52.44', 'learning_rate': '1.181e-05', 'epoch': '2.987'}
{'eval_loss': '0.9419', 'eval_accuracy': '0.8916', 'eval_f1': '0.4762', 'eval_recall': '0.5417', 'eval_precision': '0.4248', 'eval_roc_auc': '0.7341', 'eval_runtime': '13.31', 'eval_samples_per_second': '198.2', 'eval_steps_per_second': '6.235', 'epoch': '3'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'loss': '0.2081', 'grad_norm': '121.1', 'learning_rate': '1.164e-05', 'epoch': '3.03'}
{'loss': '0.1693', 'grad_norm': '80.56', 'learning_rate': '1.147e-05', 'epoch': '3.074'}
{'loss': '0.2084', 'grad_norm': '10.53', 'learning_rate': '1.13e-05', 'epoch': '3.117'}
{'loss': '0.2139', 'grad_norm': '6.196', 'learning_rate': '1.113e-05', 'epoch': '3.16'}
{'loss': '0.2136', 'grad_norm': '1.822', 'learning_rate': '1.096e-05', 'epoch': '3.203'}
{'loss': '0.3055', 'grad_norm': '2.411', 'learning_rate': '1.079e-05', 'epoch': '3.247'}
{'loss': '0.125', 'grad_norm': '0.09582', 'learning_rate': '1.062e-05', 'epoch': '3.29'}
{'loss': '0.2539', 'grad_norm': '1.07', 'learning_rate': '1.045e-05', 'epoch': '3.333'}
{'loss': '0.2756', 'grad_norm': '20.44', 'learning_rate': '1.028e-05', 'epoch': '3.377'}
{'loss': '0.2186', 'grad_norm': '0.1979', 'learning_rate': '1.011e-05', 'epoch': '3.42'}
{'loss': '0.1399', 'grad_norm': '0.06666', 'learning_rate': '9.942e-06', 'epoch': '3.463'}
{'loss': '0.1457', 'grad_norm': '0.1201', 'learning_rate': '9.773e-06', 'epoch': '3.506'}
{'loss': '0.253', 'grad_norm': '63.62', 'learning_rate': '9.603e-06', 'epoch': '3.55'}
{'loss': '0.1484', 'grad_norm': '91.53', 'learning_rate': '9.434e-06', 'epoch': '3.593'}
{'loss': '0.2499', 'grad_norm': '51.19', 'learning_rate': '9.264e-06', 'epoch': '3.636'}
{'loss': '0.1747', 'grad_norm': '0.2107', 'learning_rate': '9.094e-06', 'epoch': '3.68'}
{'loss': '0.2678', 'grad_norm': '0.5775', 'learning_rate': '8.925e-06', 'epoch': '3.723'}
{'loss': '0.1643', 'grad_norm': '0.02804', 'learning_rate': '8.755e-06', 'epoch': '3.766'}
{'loss': '0.2467', 'grad_norm': '9.822', 'learning_rate': '8.586e-06', 'epoch': '3.81'}
{'loss': '0.2204', 'grad_norm': '0.0621', 'learning_rate': '8.416e-06', 'epoch': '3.853'}
{'loss': '0.1857', 'grad_norm': '0.1822', 'learning_rate': '8.246e-06', 'epoch': '3.896'}
{'loss': '0.1791', 'grad_norm': '1.192', 'learning_rate': '8.077e-06', 'epoch': '3.939'}
{'loss': '0.1607', 'grad_norm': '110.3', 'learning_rate': '7.907e-06', 'epoch': '3.983'}
{'eval_loss': '1.749', 'eval_accuracy': '0.909', 'eval_f1': '0.469', 'eval_recall': '0.4417', 'eval_precision': '0.5', 'eval_roc_auc': '0.6987', 'eval_runtime': '13.3', 'eval_samples_per_second': '198.4', 'eval_steps_per_second': '6.241', 'epoch': '4'}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'train_runtime': '1388', 'train_samples_per_second': '79.8', 'train_steps_per_second': '4.991', 'train_loss': '0.3789', 'epoch': '4'}

[I 2026-09-22 12:05:32,947] Trial 9 finished with value: 0.5209125475285171 and parameters: {'learning_rate': 2.3507838215453306e-05, 'num_train_epochs': 6, 'per_device_train_batch_size': 8, 'weight_decay': 0.04464235683368935}. Best is trial 4 with value: 0.5269230769230769.

{'eval_loss': '0.7387', 'eval_accuracy': '0.9045', 'eval_f1': '0.5209', 'eval_recall': '0.5708', 'eval_precision': '0.479', 'eval_roc_auc': '0.7543', 'eval_runtime': '13.33', 'eval_samples_per_second': '197.9', 'eval_steps_per_second': '6.228', 'epoch': '4'}
Best Stage 1 params: {'learning_rate': 3.33374837226629e-05, 'num_train_epochs': 3, 'per_device_train_batch_size': 8, 'weight_decay': 0.004947668289613083}
Best Stage 1 validation F1: 0.5269230769230769

## Train final Stage 1 model with best hyperparameters

In [29]:
best_s1 = study_s1.best_params

args_s1 = TrainingArguments(
    output_dir="./best_s1",
    num_train_epochs=best_s1["num_train_epochs"],
    per_device_train_batch_size=best_s1["per_device_train_batch_size"],
    per_device_eval_batch_size=16,
    learning_rate=best_s1["learning_rate"],
    weight_decay=best_s1["weight_decay"],
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    remove_unused_columns=False,
    logging_steps=50,
    disable_tqdm=False,
    report_to=[],
)

model_s1 = model_init_s1()
trainer_s1 = WeightedTrainerSingleLabel(
    model=model_s1,
    args=args_s1,
    train_dataset=train_dataset_1,
    eval_dataset=val_dataset_1,
    compute_metrics=compute_metrics_s1,
    class_weights=class_weights_s1,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)
trainer_s1.train()

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=3465, training_loss=0.4257100454828612, metrics={'train_runtime': 1044.7432, 'train_samples_per_second': 53.023, 'train_steps_per_second': 3.317, 'total_flos': 3643759227916800.0, 'train_loss': 0.4257100454828612, 'epoch': 3.0})

In [30]:
# Threshold tuning on VALIDATION for Stage 1.
pred1_val = trainer_s1.predict(val_dataset_1)
probs1_val = torch.softmax(torch.tensor(pred1_val.predictions), dim=-1)[:, 1].numpy()

precision_curve_s1, recall_curve_s1, thresholds_s1 = precision_recall_curve(y_val, probs1_val)
f1_curve_s1 = 2 * precision_curve_s1 * recall_curve_s1 / (precision_curve_s1 + recall_curve_s1 + 1e-12)
best_idx_s1 = np.argmax(f1_curve_s1[:-1])
best_threshold_s1 = thresholds_s1[best_idx_s1]

print(f"Stage 1 best threshold (max F1 on validation): {best_threshold_s1:.4f}")
print(f"  validation precision={precision_curve_s1[best_idx_s1]:.4f} "
      f"recall={recall_curve_s1[best_idx_s1]:.4f} f1={f1_curve_s1[best_idx_s1]:.4f}")

Stage 1 best threshold (max F1 on validation): 0.5101
  validation precision=0.4890 recall=0.5542 f1=0.5195

In [31]:
pred1 = trainer_s1.predict(test_dataset_1)
pred_label1 = pred1.predictions.argmax(axis=1)

probs1_test = torch.softmax(torch.tensor(pred1.predictions), dim=-1)[:, 1].numpy()
pred_label1_tuned = (probs1_test >= best_threshold_s1).astype(int)

print("Stage 1 classification report @ default threshold (0.5) -- test set:")
print(classification_report(y_test, pred_label1))

print(f"\nStage 1 classification report @ tuned threshold ({best_threshold_s1:.4f}) -- test set:")
print(classification_report(y_test, pred_label1_tuned))

Stage 1 classification report @ default threshold (0.5) -- test set:
              precision    recall  f1-score   support

           0       0.95      0.94      0.95      4796
           1       0.46      0.52      0.49       480

    accuracy                           0.90      5276
   macro avg       0.71      0.73      0.72      5276
weighted avg       0.91      0.90      0.90      5276


Stage 1 classification report @ tuned threshold (0.5101) -- test set:
              precision    recall  f1-score   support

           0       0.95      0.94      0.95      4796
           1       0.46      0.52      0.49       480

    accuracy                           0.90      5276
   macro avg       0.71      0.73      0.72      5276
weighted avg       0.91      0.90      0.90      5276

In [32]:
trainer_s1.save_model("./model_stage1_weighted_optuna")
tokenizer.save_pretrained("./model_stage1_weighted_optuna")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./model_stage1_weighted_optuna/tokenizer_config.json',
 './model_stage1_weighted_optuna/tokenizer.json')

In [33]:
from huggingface_hub import HfApi

api = HfApi()

api.create_repo(
    repo_id="evelnap/hs-stage1-weighted-optuna",
    repo_type="model",
    exist_ok=True
)

api.upload_folder(
    folder_path="./model_stage1_weighted_optuna",
    repo_id="evelnap/hs-stage1-weighted-optuna",
    repo_type="model"
)

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

CommitInfo(commit_url='https://huggingface.co/evelnap/hs-stage1-weighted-optuna/commit/f7093975f4bb8a78f808c422535e28522bd3617b', commit_message='Upload folder using huggingface_hub', commit_description='', oid='f7093975f4bb8a78f808c422535e28522bd3617b', pr_url=None, repo_url=RepoUrl('https://huggingface.co/evelnap/hs-stage1-weighted-optuna', endpoint='https://huggingface.co', repo_type='model', repo_id='evelnap/hs-stage1-weighted-optuna'), pr_revision=None, pr_num=None)

# Stage 2 — 5-Label Toxicity Type (Oversampling + Optuna + Threshold)

In [ ]:
df_toxic = df_main[df_main["toxicity"] == 1].copy()

In [ ]:
# This variant keeps ALL 5 labels.
LABEL_COLS = [
    "insults",
    "identity_attack",
    "threat_incitement_to_violence",
    "profanity_obscenity",
    "sexually_explicit",
]

X = df_toxic["processed_text"]
y2 = df_toxic[LABEL_COLS]

In [ ]:
train_val_df_s2, test_df_s2 = train_test_split(df_toxic, test_size=0.2, random_state=42)
train_df_s2, val_df_s2 = train_test_split(train_val_df_s2, test_size=0.125, random_state=42)

train_df_s2 = train_df_s2[["processed_text"] + LABEL_COLS].copy()
val_df_s2 = val_df_s2[["processed_text"] + LABEL_COLS].copy()
test_df_s2 = test_df_s2[["processed_text"] + LABEL_COLS].copy()

print("Stage 2 split sizes:", {"train": len(train_df_s2), "val": len(val_df_s2), "test": len(test_df_s2)})

In [ ]:
# Random oversampling of minority-label rows for Stage 2 (multi-label). For each label
# whose positive count is below the most frequent label's count, duplicate (with
# replacement) rows carrying that label until the gap is filled. Only the TRAIN split is
# resampled -- val/test keep their natural distribution.
def oversample_multilabel(df, label_cols, random_state=42):
    max_count = df[label_cols].sum().max()
    parts = [df]
    for col in label_cols:
        col_count = df[col].sum()
        n_needed = int(max_count - col_count)
        if n_needed > 0:
            minority_rows = df[df[col] == 1]
            if len(minority_rows) > 0:
                parts.append(minority_rows.sample(n=n_needed, replace=True, random_state=random_state))
    balanced = pd.concat(parts).sample(frac=1, random_state=random_state).reset_index(drop=True)
    return balanced

In [ ]:
# Oversample the TRAIN split only. val/test keep their natural distribution.
print("Before oversampling:", {c: int(train_df_s2[c].sum()) for c in LABEL_COLS})
train_df_s2 = oversample_multilabel(train_df_s2, LABEL_COLS, random_state=42)
print("After oversampling:", {c: int(train_df_s2[c].sum()) for c in LABEL_COLS})

In [ ]:
train_df_s2["label"] = train_df_s2[LABEL_COLS].astype(float).values.tolist()
val_df_s2["label"] = val_df_s2[LABEL_COLS].astype(float).values.tolist()
test_df_s2["label"] = test_df_s2[LABEL_COLS].astype(float).values.tolist()

train_df_s2 = train_df_s2[["processed_text", "label"]]
val_df_s2 = val_df_s2[["processed_text", "label"]]
test_df_s2 = test_df_s2[["processed_text", "label"]]

In [ ]:
dataset_s2 = DatasetDict({
    "train": Dataset.from_pandas(train_df_s2.reset_index(drop=True)),
    "validation": Dataset.from_pandas(val_df_s2.reset_index(drop=True)),
    "test": Dataset.from_pandas(test_df_s2.reset_index(drop=True))
})

In [ ]:
MODEL_NAME = "indolem/indobertweet-base-uncased"
tokenizer_s2 = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_s2(batch):
    return tokenizer_s2(batch["processed_text"], padding="max_length", truncation=True, max_length=128)

tokenized_datasets_2 = dataset_s2.map(tokenize_s2, batched=True)
tokenized_datasets_2 = tokenized_datasets_2.remove_columns(["processed_text"])
tokenized_datasets_2 = tokenized_datasets_2.rename_column("label", "labels")
tokenized_datasets_2.set_format("torch")

train_dataset_2 = tokenized_datasets_2["train"]
val_dataset_2 = tokenized_datasets_2["validation"]
test_dataset_2 = tokenized_datasets_2["test"]

In [ ]:
from sklearn.metrics import roc_auc_score

def compute_metrics_s2(eval_pred):
    logits, labels = eval_pred
    preds = (logits > 0).astype(int)
    return {
        "f1_micro": f1_score(labels, preds, average="micro"),
        "f1_macro": f1_score(labels, preds, average="macro"),
        "accuracy": accuracy_score(labels, preds),
        "recall_micro": recall_score(labels, preds, average="micro", zero_division=0),
        "precision_micro": precision_score(labels, preds, average="micro", zero_division=0),
    }

## Optuna search — Stage 2 (oversampled)

In [ ]:
def model_init_s2():
    return AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=len(LABEL_COLS),
        problem_type="multi_label_classification"
    )

def objective_s2(trial):
    lr = trial.suggest_float("learning_rate", 1e-5, 5e-5, log=True)
    epochs = trial.suggest_int("num_train_epochs", 3, 6)
    batch_size = trial.suggest_categorical("per_device_train_batch_size", [8, 16])
    weight_decay = trial.suggest_float("weight_decay", 0.0, 0.1)

    args = TrainingArguments(
        output_dir=f"./optuna_s2/trial_{trial.number}",
        num_train_epochs=epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=16,
        learning_rate=lr,
        weight_decay=weight_decay,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1_macro",
        greater_is_better=True,
        logging_steps=50,
        disable_tqdm=True,
        report_to=[],
    )

    trainer = Trainer(
        model_init=model_init_s2,
        args=args,
        train_dataset=train_dataset_2,
        eval_dataset=val_dataset_2,
        compute_metrics=compute_metrics_s2,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
    )
    trainer.train()
    metrics = trainer.evaluate()
    return metrics["eval_f1_macro"]

study_s2 = optuna.create_study(direction="maximize", study_name="stage2_oversampling")
study_s2.optimize(objective_s2, n_trials=N_TRIALS)

print("Best Stage 2 params:", study_s2.best_params)
print("Best Stage 2 validation macro F1:", study_s2.best_value)

## Train final Stage 2 model with best hyperparameters

In [ ]:
best_s2 = study_s2.best_params

args_s2 = TrainingArguments(
    output_dir="./best_s2",
    num_train_epochs=best_s2["num_train_epochs"],
    per_device_train_batch_size=best_s2["per_device_train_batch_size"],
    per_device_eval_batch_size=16,
    learning_rate=best_s2["learning_rate"],
    weight_decay=best_s2["weight_decay"],
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,
    logging_steps=50,
    disable_tqdm=False,
    report_to=[],
)

model_s2 = model_init_s2()
trainer_s2 = Trainer(
    model=model_s2,
    args=args_s2,
    train_dataset=train_dataset_2,
    eval_dataset=val_dataset_2,
    compute_metrics=compute_metrics_s2,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)
trainer_s2.train()

In [ ]:
# Per-label threshold tuning on VALIDATION.
pred2_val = trainer_s2.predict(val_dataset_2)
probs_val = 1 / (1 + np.exp(-pred2_val.predictions))
y_val_true = pred2_val.label_ids

best_thresholds_s2 = {}
for i, label_name in enumerate(LABEL_COLS):
    p_curve, r_curve, t_curve = precision_recall_curve(y_val_true[:, i], probs_val[:, i])
    f1_curve = 2 * p_curve * r_curve / (p_curve + r_curve + 1e-12)
    best_idx = np.argmax(f1_curve[:-1])
    best_thresholds_s2[label_name] = float(t_curve[best_idx])
    print(f"{label_name}: best threshold (val)={t_curve[best_idx]:.4f} "
          f"precision={p_curve[best_idx]:.4f} recall={r_curve[best_idx]:.4f} f1={f1_curve[best_idx]:.4f}")

threshold_vector_s2 = np.array([best_thresholds_s2[c] for c in LABEL_COLS])

In [ ]:
pred2 = trainer_s2.predict(test_dataset_2)
probs = 1 / (1 + np.exp(-pred2.predictions))
y_true = pred2.label_ids

pred_label2 = (probs > 0.5).astype(int)
pred_label2_tuned = (probs >= threshold_vector_s2).astype(int)

print("Stage 2 classification report @ default threshold (0.5) -- test set:")
print(classification_report(y_true, pred_label2, target_names=LABEL_COLS))

print("\nStage 2 classification report @ per-label tuned thresholds -- test set:")
print(classification_report(y_true, pred_label2_tuned, target_names=LABEL_COLS))